### ISSUE TITLE
long java.lang.Long.longValue()

### ISSUE THREAD

**Issue by anwh** [stashenergy/react-native-msal#10]
Hi, i get this error when calling msalClient.acquireToken:

` WARN  [Error: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference]`

The params are good, I checked them.

_invalid scopes parameters_

**Comment by genesisemmloh** [comment]
why it was closed? can i know the solution?

**Comment by josmithua** [comment]
@genesisemmloh They edited their post when it was closed:

> _invalid scopes parameters_
