### ISSUE TITLE
IOS getAccount method crash RN app if MSALAccount is nil

### ISSUE THREAD

**Issue by zounasL** [stashenergy/react-native-msal#102]
**Describe the bug**
IOS RN app crash if objective-c getAccount return nil. There isn't nil check for the MSAL account which will be resolved in the getAccount method.

**To Reproduce**
1. Make the IOS code return nil MSALAccount
2. RN App crash because there isn't check for nil account 

**Expected behavior**
Raise null account error if getAccount return null

** Please complete the following information:**
 - `react-native-msal` version: 3.1.2
 - `react-native` version: 0.63.4
 - Platform: IOS

**Comment by josmithua** [comment]
Thanks, there's currently a few places where we should be checking for `nil`. Will fix soon.

**Comment by josmithua** [comment]
This will be fixed in v4 (currently fixed in v4 beta)

**Comment by zounasL** [comment]
The beta version is looking awesome, just wondering which would be better practise for the nil check. Should it retrun reject instead of resolve? In that case it also have affect to the getAccounts method

It doesn't really  matter that much but now we need to do undefined check in JS, but if it return reject then catch will handle it?

Don't know, someone who is more wiser than me can comment on this =D... Anywho, Dude it is looking lit.

**Comment by josmithua** [comment]
@zounasL Returning `nil` is not an error in the iOS library, so I don't think it should be an error in this library.

For the `getAccounts` method, I made sure to return an empty array when the native method returns `nil`
