### ISSUE TITLE
Authentication Error MSALErrorDescriptionKey

### ISSUE THREAD

**Issue by tommycp96** [stashenergy/react-native-msal#106]
Hi Joshua,

Good day! Would like to get check with you regarding the below problem that I facing
<img width="324" alt="Screen Shot 2021-09-01 at 1 37 27 PM" src="https://user-images.githubusercontent.com/40844706/131623686-619dd05e-5755-4c06-94f4-edc27dbe591d.png">

This issue happened after I approve my sign-in request from my authenticator app and redirect back to our application.
And also we already granted the consent from our Azure Portal.

this is my code config and implementation for your reference
<img width="884" alt="Screen Shot 2021-09-01 at 1 38 58 PM" src="https://user-images.githubusercontent.com/40844706/131624061-787f36df-c0fa-408d-a82a-ec906fe58e7b.png">

So, would like to get some of your insight or everyone in here that having the same issue, thanks!

Best regards,
Tommy

**Comment by josmithua** [comment]
The error is pretty explanatory: you should not have `openid`, `profile`, or `offline_access` in your scopes. In your case, just have `User.Read` and `Mail.Read`. 

And btw, I’m surprised it’s “working”, as scopes should be specified as individual array elements:

```js
const scopes = [“User.Read”, “Mail.Read”];
```

**Comment by tommycp96** [comment]
Omg you're right Josh, you saved my life hahaha. Now our app is working fine, thanks in advance!
