### ISSUE TITLE
Performance issues for android 10 and lower devices

### ISSUE THREAD

**Issue by kattamudi-karthik** [stashenergy/react-native-msal#111]
Hi , 

We are seeing performance issues for android 10 and lower devices . It is taking around 3-5 seconds for lower end devices . 
Also one question do we have cache enabled for android and ios using this library ? If it is not enabled can we use AsyncStorage ?

**Comment by josmithua** [comment]
This React Native library is a thin wrapper around the native Android/Java and iOS/obj-c MSAL libraries. If you are seeing performance issues they are most likely with the native libraries. 

Where exactly are you seeing the 3-5 second hang?

**Comment by josmithua** [comment]
Also I'm not sure I understand what you want to cache? There is nothing really to cache, the native libraries handle caching all necessary information, including refresh tokens.

**Comment by kattamudi-karthik** [comment]
We have logged the performance numbers for acquireTokenSilent Method then we observed it is taking 3-5 seconds in our app specially for android 10 and 9 devices . 
I was thinking the cache managed using  this npm package .But looks like as you said it is taken care of native modules . 
I was confused with this configuration object . 
export interface MSALConfiguration {
    auth: {
        clientId: string;
        authority?: string;
        knownAuthorities?: string[];
        redirectUri?: string;
    };
    /**
     * @platform web
     */
    cache?: Configuration['cache'] & {
        cacheLocation?: 'localStorage' | 'sessionStorage'| 'AsyncStorage';
    };
}

**Comment by kattamudi-karthik** [comment]
Is it possible to upgrade this package to use the latest native modules with respect to android and ios  to get the new features and performance benefits  ?

**Comment by josmithua** [comment]
The beta version of this library (v4.0.0-beta.6) uses the latest version of Android MSAL (2.1.x). You can try it out and let me know how it works.

I'm using the beta version in 2 production apps and don't see these performance issues. It's definitely slower in an Android emulator but running a production build on a real device seems fine

**Comment by josmithua** [comment]
Are you passing `forceRefresh: true` to acquireTokenSilent? If so it will take significantly longer. I recommend you leave it out/set it to false except when necessary

**Comment by kattamudi-karthik** [comment]
Thanks for immediate reply .
We tested this numbers in a production app . We are seeing this performance issues only with android 10 and lower end devices. 
We are not using the forceRefresh flag. 
But as you suggested we will upgrade the package and will test it one more time . 
We are also trying to come with a simple create react native app and want to test numbers to eliminate issues from our app side .

**Comment by josmithua** [comment]
> Can I know what are the numbers you are seeing in the idle case for generating token in android and ios ?

You want to know how long the `acquireTokenSilent` call is taking?

Using this code:

```js
const t0 = performance.now();
const result = await b2cClient.acquireTokenSilent({ scopes });
const t1 = performance.now();
console.log('acquireTokenSilent time:', t1 - t0);

```

This is the logs on an Android Emulator running Android 10 (times are in ms, first log was the first call to acquireTokenSilent):
```
Running app on Android SDK built for x86
acquireTokenSilent time: 1173.0789549999754
acquireTokenSilent time: 353.5563390000025
acquireTokenSilent time: 736.4847310000332
acquireTokenSilent time: 167.4479360000114
acquireTokenSilent time: 162.21183300000848
acquireTokenSilent time: 408.4193320000195
acquireTokenSilent time: 96.29573900002288
acquireTokenSilent time: 124.71711500000674
acquireTokenSilent time: 198.91302800003905
acquireTokenSilent time: 177.01723100000527
acquireTokenSilent time: 279.00276900001336
acquireTokenSilent time: 396.11039400001755
acquireTokenSilent time: 399.76416700001573
acquireTokenSilent time: 125.16758499998832
acquireTokenSilent time: 235.96085200004745
acquireTokenSilent time: 200.29111099999864
```

On a real Android device, running Android 10 (OnePlus 5T):
```
Running app on ONEPLUS A5010
acquireTokenSilent time: 3650.659685999155
acquireTokenSilent time: 913.9507809951901
acquireTokenSilent time: 142.69598999619484
acquireTokenSilent time: 237.05036399513483
acquireTokenSilent time: 208.34093799442053
acquireTokenSilent time: 217.33026099950075
acquireTokenSilent time: 163.6534890010953
acquireTokenSilent time: 154.08046800643206
acquireTokenSilent time: 153.74838499724865
acquireTokenSilent time: 194.41541600227356
acquireTokenSilent time: 159.5617709979415
acquireTokenSilent time: 128.96031299978495
```

On an Android 11 emulator:
```
acquireTokenSilent time: 887.4279999998398
acquireTokenSilent time: 764.7530000000261
acquireTokenSilent time: 311.4330000001937
acquireTokenSilent time: 194.71299999998882
acquireTokenSilent time: 705.7060000000056
acquireTokenSilent time: 421.2489999998361
acquireTokenSilent time: 413.7919999998994
acquireTokenSilent time: 236.82400000002235
acquireTokenSilent time: 165.82399999978952
acquireTokenSilent time: 177.0339999999851
acquireTokenSilent time: 223.84199999971315
acquireTokenSilent time: 199.51300000026822
acquireTokenSilent time: 204.14500000001863
acquireTokenSilent time: 196.5749999997206
acquireTokenSilent time: 221.6520000002347
acquireTokenSilent time: 166.36500000022352
```

On an iPhone 12 simulator:
```
Running app on iPhone 12
acquireTokenSilent time: 35.5041880607605
acquireTokenSilent time: 44.642098009586334
acquireTokenSilent time: 31.507376968860626
acquireTokenSilent time: 31.167244970798492
acquireTokenSilent time: 31.163259983062744
acquireTokenSilent time: 28.939554035663605
acquireTokenSilent time: 31.200767040252686
acquireTokenSilent time: 33.68509900569916
acquireTokenSilent time: 33.196460008621216
```

**Comment by kattamudi-karthik** [comment]
Looks like  Running app on ONEPLUS A5010 Is taking time for you as well . 
- acquireTokenSilent time: 3650.659685999155
- acquireTokenSilent time: 913.9507809951901

We are also calculating the performance numbers in the real app as per your code sample . 
We are also trying to come up with a similar test app and want to test on different variety of devices (samsung ,oppo etc) , we are facing some internal challenges with the test app . We will get back to you asap . 
There is lot of difference between simulators vs Actual Devices with respective this numbers . The numbers are little bit high with the Actual devices . 
IOS and Android 11 are pretty much fast . Android 10 , 9 ,8 are where the numbers are high and start of our app we have different apis in which we are calling them in parallel in which the the token will be generated for each resources separately as they will not available in the cache . So in app start if we are taking 3650 milli seconds to generate the token and get the response back to the user . In a way we are blocking the user for around 4 seconds which is not giving as great user experience . 

Can you please let us know what is the approx bandwidth you have tested those numbers ? 
If you can share your test app that you have used to measure the metrics that would be great .

**Comment by kattamudi-karthik** [comment]
Can you please give an update on the above queries

**Comment by josmithua** [comment]
> Looks like Running app on ONEPLUS A5010 Is taking time for you as well .
> 
> * acquireTokenSilent time: 3650.659685999155
> * acquireTokenSilent time: 913.9507809951901

Those were for the first two calls on app startup, the rest were fairly quick.

> Can you please let us know what is the approx bandwidth you have tested those numbers ?

My test was fairly unscientific, so I can't say regarding the bandwidth, except that is was probably around 300-500mbps

> Can you please let us know with which msal version you are seeing this numbers ?

It was the latest beta version, v4.0.0-beta.6

> If you can share your test app that you have used to measure the metrics that would be great .

I tested in my company's production app. But you could easily set up the example app in this repo to run these simple tests.

**Comment by kattamudi-karthik** [comment]
Thank you Josmithua for your reply .We used a simple app and tested the numbers in android 10 and lower we are getting the little bit higher numbers . For the first call for each unique resource we are seeing the number as 3-6  seconds . Probably issue might with the core native android package .

**Comment by josmithua** [comment]
Is it possible for me to try your simple app? Through a private GitHub repo or something?
