### ISSUE TITLE
MSAL auth not opening on build versions of app on IOS

### ISSUE THREAD

**Issue by martinowren** [stashenergy/react-native-msal#116]
**Describe the bug**
For a while we have been developing an app locally with USB connected device. We tried to do a testflight, but when acquireToken is called nothing happens. The pca is already defined so we are kinda lost atm. 

**Expected behavior**
The standard browser to open with microsoft login

**Screenshots**

** Please complete the following information:**
 - `react-native-msal` version: 3.1.2
 - `react-native` version: 0.65.1
 - Platform: IOS
 - Browser : Safari

**Additional context**

**Comment by Drzaln** [comment]
Hi @martinowren did you find workaround for this? I'm facing this bug too, thanks
