### ISSUE TITLE
Crash at com.microsoft.identity.common.internal.providers.oauth2.BrowserAuthorizationFragment.createCustomTabResponseIntent BrowserAuthorizationFragment.java

### ISSUE THREAD

**Issue by richshepard** [stashenergy/react-native-msal#118]
**Describe the bug**
When trying to authenticate a user with the following:

```
const msalClient = new PublicClientApplication(this._msalConfig, false);
await msalClient.init();
const result: MSALResult = await msalClient.acquireToken(acquireTokenParams);
```

we get the following crash

```
com.microsoft.identity.common.internal.providers.oauth2.BrowserAuthorizationFragment.createCustomTabResponseIntent
BrowserAuthorizationFragment.java, line 77
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Class.getName()' on a null object reference
```

After a quick search I found this:

[https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/975](https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/975)

which is the same but fixed so I can only imaging that the currect version of react-native-msal uses 1.5.0 of microsoft-authentication-library-for-android.

**To Reproduce**
Run the following code, not sure if this is an Android 8 think, it definately seems to be handset specifig:

```
const msalClient = new PublicClientApplication(this._msalConfig, false);
await msalClient.init();
const result: MSALResult = await msalClient.acquireToken(acquireTokenParams);
```

** Please complete the following information:**
 - `react-native-msal` version: 3.1.2
 - `react-native` version: 0.63.2
 - Platform: Android 8

**Comment by josmithua** [comment]
Hi @richshepard, just wondering if your issue was resolved?
