### ISSUE TITLE
IOS Configuration issue

### ISSUE THREAD

**Issue by dusanjovanov** [stashenergy/react-native-msal#12]
I'm trying to configure the AppDelegate callback as per your the MSAL OBJC docs.
I'm not sure where to put this code: 
```
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
    return [MSALPublicClientApplication handleMSALResponse:url 
                                         sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}
```
This is my AppDelegate.m file:
![image](https://user-images.githubusercontent.com/20474783/80944754-929f5280-8dea-11ea-950c-b2c4e3e430d6.png)

If I replace the `return YES` line with the code you provided I get variable not found errors.

Although the redirection works, and I can login,  I sometimes get this error:
```
get token error [Error: Error Domain=com.apple.AuthenticationServices.WebAuthenticationSession Code=3 "The UIWindowScene for the returned window was not in the foreground active state." UserInfo={NSDebugDescription=The UIWindowScene for the returned window was not in the foreground active state.}]
```
Is that step truly necessary ?

**Comment by josmithua** [comment]
The `application` method goes anywhere in the AppDelegate.m file... See [example/ios/example/AppDelegate.m](https://github.com/stashenergy/react-native-msal/blob/master/example/ios/example/AppDelegate.m)
