### ISSUE TITLE
on android i'm having this error:  [Error: Attempt to invoke interface method 'com.facebook.react.bridge.ReadableArray com.facebook.react.bridge.ReadableMap.getArray(java.lang.String)' on a null object reference]

### ISSUE THREAD

**Issue by ayushi023** [stashenergy/react-native-msal#124]
I'm trying to implement login with microsoft in my react native application

on IOS is working correctly

but on android i'm having this error:

[Error: Attempt to invoke interface method 'com.facebook.react.bridge.ReadableArray com.facebook.react.bridge.ReadableMap.getArray(java.lang.String)' on a null object reference]

<img width="579" alt="Screenshot_2021-10-28_at_4 39 54_PM" src="https://user-images.githubusercontent.com/38783786/139274718-6260a5d2-ad2d-4145-97cd-38ea643410bc.png">

 try {
    await pca.init();
    const user = await pca.acquireToken(); // I think the error happens with this line

        } catch (error) {
            console.error('Problem in configuration/setup:', error);
        }

**Comment by josmithua** [comment]
Hi there, you need to provide one or more scopes to the acquireToken call. 

```js
const res = await pca.acquireToken({ scopes: ["your scope here"] })
```
