### ISSUE TITLE
acquireToken does not show a login screen - ANDROID

### ISSUE THREAD

**Issue by Goutham-Elangovan** [stashenergy/react-native-msal#126]
**Bug Description:**
I have followed the docs and configured all necessary steps which includes App registration, Signature hash generation, modifying build.gradle, Android manifest etc. 

**Android Manifest**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.dcomobile">

  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

  <application android:name=".MainApplication" android:label="@string/app_name" android:icon="@mipmap/ic_launcher" android:roundIcon="@mipmap/ic_launcher_round" android:allowBackup="false" android:theme="@style/AppTheme">
    <activity android:name=".MainActivity" android:label="@string/app_name" android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode" android:launchMode="singleTask" android:windowSoftInputMode="adjustResize">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>
    <activity android:name="com.microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msauth" android:host="com.xxxxx" android:path="/xxxxxxxxx=" />
      </intent-filter>
    </activity>
  </application>
</manifest>
```

**build.grade** has the following included
```
maven {
      url "https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1"
      }

```

**loginHandler**
```
const config1: MSALConfiguration = {
      auth: {
        clientId: 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx',
        authority:
          'https://login.microsoftonline.com/xxxxxxxxxxx',
      },
    };

    // Option 2: Skips init, so you can call it yourself and handle errors
    //const pca = new MSALClient(config, false);
    const pca = new PublicClientApplication(config1);
    try {
      await pca.init();
    } catch (error) {
      console.error('Problem in configuration/setup:', error);
    }

    const scopes: any = Platform.select({android: ["openid", "profile", "email", "AuditLog.Read.All", "Directory.Read.All", "User.Read", "User.Read.All"], ios: []});
   // const scopes: any = ["openid", "profile", "email", "AuditLog.Read.All", "Directory.Read.All", "User.Read", "User.Read.All"];
    const params: MSALInteractiveParams = {
      scopes,
    };

    let accessToken: any;
    let accountWithNoScopes: any;
    try {
      const result: MSALResult | undefined = await pca.acquireToken(params);
      console.log('Login success', result);
}

```
**Logcat log** 
`D/RNMSALModule: {"account_mode":"MULTIPLE","broker_redirect_uri_registered":false,"authority":"https:\/\/login.microsoftonline.com\/xxxxxxxxxx","client_id":"xxxxxxxxx","redirect_uri":"msauth:\/\/com.xxxxx\/xxxxx","authorities":[{"default":true,"type":"AAD","audience":{"type":"AzureADMyOrg","tenant_id":"xxxxxxx"}}]}`

If login button is clicked again then logcat shows, 

```
W/LocalMSALController:getDeviceMode:  [2021-11-04 10:44:20 - thread_name : pool-9-thread-2, correlation_id : 67769151-f33d-4f6a-94e9-ab6c8a4e15c8] LocalMSALController is not eligible to use the broker. Do not check sharedDevice mode and return false immediately. Android 30
W/Telemetry:  [2021-11-04 10:44:20 - thread_name : main, correlation_id : UNSET] Telemetry is disabled because the Telemetry context or configuration is null Android 30
```

I went through the docs and understood that msal_config.json is no more needed so I removed it. 

**Expected Behavior:**
Should be presented with a MS login screen

**Environment Information:**
 - `react-native-msal` version: ^4.0.0-beta.7
 - `react-native` version: 0.65.1
 - Platform: Android only, works fine with iOS

Could you please help me with this? :)

**Comment by josmithua** [comment]
Do you log the error that acquireToken throws, if any? I believe `openid` should not be in your scopes. And maybe `profile` too

**Comment by Goutham-Elangovan** [comment]
Thanks for your reply. acquireToken does not throw anything in the console unfortunately. I have tried removing `openid` and `profile` as well but no luck.

**Comment by Goutham-Elangovan** [comment]
Hi @josmithua any updates on the above? Android is not allowing me to provide empty scopes.

**Comment by josmithua** [comment]
Yeah you have to provide at least one scope for Android, a limitation of the underlying Android MSAL library.

I'm not sure what else it would be besides a problem with your scopes. You have scopes defined in your app in the azure portal?

**Comment by Goutham-Elangovan** [comment]
Yes I have defined. iOS works perfectly fine.

**Comment by Goutham-Elangovan** [comment]
The issue is fixed. Another library was messing up the webview to open in Android.

**Comment by josmithua** [comment]
Glad you got it working! Do you mind sharing what library that was, for others who might come across this issue? Thanks.

**Comment by tanujchawla** [comment]
@Goutham-Elangovan I'm facing a similar issue, could you please share which library was causing an issue and how did you resolve that?

**Comment by Goutham-Elangovan** [comment]
Hey, I was previously using https://github.com/FormidableLabs/react-native-app-auth for my authentication but it didn't solve my use case so I switched to MSAL. I did not uninstall that package before installing msal hence the problem.
