### ISSUE TITLE
Attempt to invoke virtual method 'boolean com.microsoft.identity.common.internal.authorities.Authority.getDefault()' on a null object reference

### ISSUE THREAD

**Issue by jasonc-forerunnersw** [stashenergy/react-native-msal#127]
**Bug Description:**
I get this error when calling pca.init().  This only happen if I supply an authority.  Otherwise it hangs in acquireToken

top of call stack:
class:'com.microsoft.identity.client.PublicClientApplicationConfiguration'
file:'PublicClientApplicationConfiguration.java'
lineNumber:408
methodName:'checkDefaultAuthoritySpecified'

class:'com.microsoft.identity.client.PublicClientApplicationConfiguration'
file:'PublicClientApplicationConfiguration.java'
lineNumber:463
methodName:'validateConfiguration'

Config:
static configuration: MSALConfiguration = {
    auth: {
      clientId: 'my guidf',
      redirectUri: 'msauth://com.myapp/0bemSv3ZWq95WDIYA4CMA1%2B1qb4%3D',
      authority: 'https://MyB2CDomain.b2clogin.com/MyB2CDomain.onmicrosoft.com/B2C_1_signUpIn',
      knownAuthorities: ['MyB2CDomain.b2clogin.com'],
    },
  };

**Steps To Reproduce:**
call init() with a configured authority

**Expected Behavior:**
no error.  I have looked at the source and I do not see how this can happen as the authority can/should not be null in the enumerator

**Environment Information:**
react-native-msal@^4.0.2:
  version "4.0.2"

react-native@^0.66.3:
  version "0.66.3"

 - Android , emulator, vrsion 1 
 - Browser (if applicable): [e.g. chrome, safari]

**Additional Information:**

**Comment by josmithua** [comment]
Hi there, could you try making `knownAuthorities[0]` the same as `authority`

**Comment by jasonc-forerunnersw** [comment]
If I make them the exact same value I do not get an error on init.  But I do get an error on acquireToken

Error:
Attempt to read from field 'java.lang.String com.microsoft.identity.common.internal.authorities.Authority.mAuthorityUrl' on a null object reference

class:'com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter'
file:'MsalExceptionAdapter.java'
lineNumber:51
methodName:'msalExceptionFromBaseException'

class:'com.microsoft.identity.client.PublicClientApplication$18'
file:'PublicClientApplication.java'
lineNumber:1903
methodName:'onError'


class:'com.microsoft.identity.client.PublicClientApplication$18'
file:'PublicClientApplication.java'
lineNumber:1894
methodName:'onError'


class:'com.microsoft.identity.client.PublicClientApplication$14$1'
file:'PublicClientApplication.java'
lineNumber:1558
methodName:'run'


My interactive params are 
static params: MSALInteractiveParams = {
    authority:  'https://MyB2CDomain.b2clogin.com/MyB2CDomain.onmicrosoft.com/B2C_1_signUpIn',
    scopes: ['https:// MyB2CDomain.onmicrosoft.com/API/AV.RW']
  };


If I do not supply an authority on the  acquireToken  I get this error
Error: Attempt to invoke virtual method 'android.net.Uri com.microsoft.identity.common.internal.authorities.Authority.getAuthorityUri()' on a null object reference

With the same call stack.

**Comment by jasonc-forerunnersw** [comment]
Would appreciate any insight.  These same settings work correctly in the web based solution.

**Comment by josmithua** [comment]
Sorry. Have you looked at the B2CClient class that I made for b2c applications? It's in the example/src/b2cclient.ts file

**Comment by jasonc-forerunnersw** [comment]
Yes I have.  Is there something specific?  The errors seems to be about configuration, which at this point is very simple.  The Null references seem to be happening before any server involvement.

**Comment by jasonc-forerunnersw** [comment]
After debugging into the lib found that the match for authority was failing because my base does not have a tfp in it so it does not look like a B2C.  Adding this fixed the issue.  Probably good to have a error if the authority type can not be determined.  Otherwise it is an empty object and then the NULL reference.

**Comment by josmithua** [comment]
Thanks, I will add an error (or feel free to submit a PR!)
