### ISSUE TITLE
acquireTokenSilent does not work without explicitly providing authority

### ISSUE THREAD

**Issue by k-mehta** [stashenergy/react-native-msal#128]
**Bug Description:**
If I explicitly provide a value for the "authority" parameter, the call succeeds. Excluding it results in a failure.

**Steps To Reproduce:**
```
const msalConfig: MSALConfiguration = {
  auth: {
    clientId: 'XXXXX',
    authority: 'https://login.microsoftonline.com/common/',
    redirectUri: Platform.select({
      android: 'msauth://XXXXX',
      default: undefined,
    }),
  },
  androidConfigOptions: {
    logging: { pii_enabled: false, log_level: 'INFO', logcat_enabled: true },
    broker_redirect_uri_registered: true,
  },
};

const params: MSALSilentParams = {
  account,
  scopes: requestScopes,
  forceRefresh: true,
};
```

**Expected Behavior:**
The call should work without providing the optional parameter. The authority from the original config should be respected.

**Environment Information:**
 - `react-native-msal` version: 4.0.2
 - `react-native` version: 0.66.3
 - Platform: Android (emulator on Windows)
 - Browser (if applicable): Chrome

**Additional Information:**
Exception I'm seeing:
```
{
  "nativeStackAndroid": [
    {
      "methodName": "msalExceptionFromBaseException",
      "lineNumber": 51,
      "file": "MsalExceptionAdapter.java",
      "class": "com.microsoft.identity.client.internal.controllers.MsalExceptionAdapter"
    },
    {
      "methodName": "onError",
      "lineNumber": 1903,
      "file": "PublicClientApplication.java",
      "class": "com.microsoft.identity.client.PublicClientApplication$18"
    },
    {
      "methodName": "onError",
      "lineNumber": 1894,
      "file": "PublicClientApplication.java",
      "class": "com.microsoft.identity.client.PublicClientApplication$18"
    },
    {
      "methodName": "run",
      "lineNumber": 1643,
      "file": "PublicClientApplication.java",
      "class": "com.microsoft.identity.client.PublicClientApplication$15$1"
    },
    {
      "methodName": "handleCallback",
      "lineNumber": 938,
      "file": "Handler.java",
      "class": "android.os.Handler"
    },
    {
      "methodName": "dispatchMessage",
      "lineNumber": 99,
      "file": "Handler.java",
      "class": "android.os.Handler"
    },
    {
      "methodName": "loop",
      "lineNumber": 223,
      "file": "Looper.java",
      "class": "android.os.Looper"
    },
    {
      "methodName": "main",
      "lineNumber": 7656,
      "file": "ActivityThread.java",
      "class": "android.app.ActivityThread"
    },
    {
      "methodName": "invoke",
      "lineNumber": -2,
      "file": "Method.java",
      "class": "java.lang.reflect.Method"
    },
    {
      "methodName": "run",
      "lineNumber": 592,
      "file": "RuntimeInit.java",
      "class": "com.android.internal.os.RuntimeInit$MethodAndArgsCaller"
    },
    {
      "methodName": "main",
      "lineNumber": 947,
      "file": "ZygoteInit.java",
      "class": "com.android.internal.os.ZygoteInit"
    }
  ],
  "userInfo": null,
  "message": "",
  "code": "EUNSPECIFIED",
  "line": 2568,
  "column": 45,
  "sourceURL": "http://10.0.2.2:8081/mobile/index.bundle?platform=android&dev=true&minify=false&app=XXXXX&modulesOnly=false&runModule=true"
}
```

**Comment by josmithua** [comment]
That is pretty odd. If you don't provide an authority, it should default to `https://login.microsoftonline.com/common`, as specified at https://github.com/stashenergy/react-native-msal/blob/master/android/src/main/java/com/reactnativemsal/RNMSALModule.java#L94

**Comment by k-mehta** [comment]
To be clear, this is an issue when I call `publicClientApplication.acquireTokenSilent(params)`. 

This line is probably the one that's acting up:
https://github.com/stashenergy/react-native-msal/blob/c136b3b731e209ae1ff64f3b421e48c959af9e83/android/src/main/java/com/reactnativemsal/RNMSALModule.java#L299

It's unfortunate that Microsoft doesn't have any documentation for what `PublicClientApplicationConfiguration.getDefaultAuthority()` does. That appears to be the only method that does not have any documentation. But I suspect that's the method that's not returning the value set for `authority`.
https://docs.microsoft.com/en-us/java/api/com.microsoft.identity.client.publicclientapplicationconfiguration.getdefaultauthority?view=azure-java-stable#com_microsoft_identity_client_PublicClientApplicationConfiguration_getDefaultAuthority

**Comment by josmithua** [comment]
The source is here: 
https://github.dev/AzureAD/microsoft-authentication-library-for-android/blob/a36b71e863ff7caea55357f061da132dea17f1d3/msal/src/main/java/com/microsoft/identity/client/PublicClientApplicationConfiguration.java#L398-L413

Maybe my logic for detecting what the default authority should be is buggy.

**Comment by k-mehta** [comment]
I think I have a theory about what's happening.

My MSALConfiguration is initialized with an authority (notice the trailing `/`).

`authority: 'https://login.microsoftonline.com/common/'`

In your code to create the authorities JSON array, you do a direct string comparison that's not very forgiving of different URL representations :)
https://github.com/stashenergy/react-native-msal/blob/c136b3b731e209ae1ff64f3b421e48c959af9e83/android/src/main/java/com/reactnativemsal/RNMSALModule.java#L156

So, the tenant type for the default audience gets set to "AzureADMyOrg" based on the regex match, causing the rest of the code to fail.

This is just based on reading the code and not actually running it with a debugger attached, so this is all theoretical.

**Comment by josmithua** [comment]
Yeah you're right, I plan to refactor that soon. 

However, in your original comment you said you get the error when you _don't_ provide the authority url? Oooh you meant if you don't provide it in the `acquireTokenSilent` call, not the constructor... I misinterpreted your code example, I was focused on the config object. My bad. 

Yes, once I refactor that function to be more forgiving it should fix things. Cheers :)

P.S. Your profile says you're a Microsoft employee. Can I ask if you're using/evaluating this at your work or for a personal project?

**Comment by k-mehta** [comment]
Thanks for the fix! This is currently for a personal project :)
