### ISSUE TITLE
How to force disable calling broker app on iOS?

### ISSUE THREAD

**Issue by tommycp96** [stashenergy/react-native-msal#129]
Hi @josmithua,

Hope everything is fine, at first I would like to take the opportunity to appreciate this library is really nice!
But may need some of your guides and advice on how can we disable it to automatically call the broker app(if it's installed) on iOS?
so the expected behavior that we want is when there is a Microsoft Authenticator installed on the devices we don't need to be redirected to the Authenticator and use the system browser instead to perform the authentication(login).

Because understand that for Android we can configure this either from the msal.json file or through the config provided by this library,
```
const config = {
  auth: {
    clientId: Config.auth.aad.clientId,
    authority: Config.auth.aad.authority + Config.auth.aad.tenantId,
    redirectUri:
      Platform.OS === 'android'
        ? Config.auth.aad.redirectUriAndroid
        : Config.auth.aad.redirectUriIOS
  },
  androidConfigOptions: {
    broker_redirect_uri_registered: false
  }
}
```

is there any way from the config library that we can turn it off for iOS like on Android?
Or maybe can you help to give some insights on how to disable it from the native level?

**Comment by peddiarjun** [comment]
hi @tommycp96,
You may give this a try.. 
include `webviewParameters: { ios_webviewType: Ios_MSALWebviewType.SAFARI_VIEW_CONTROLLER }` in the parameters object while calling `acquireToken(params)` method

**Comment by tommycp96** [comment]
hi @peddiarjun , 

It still redirects me to the authenticator app. Maybe I'll give you a little bit of background the goal that we would like to achieve is SSO to the web app(tableua) that integrates with our AAD also from the Azure Portal. Unfortunately, in iOS, if the session was inside the broker app, the SSO will not perform. Meaning we need to do the re-login again from the tableau side.

**Comment by ayushi023** [comment]
Hi @josmithua

Is there any way to force disable the same, I am also facing the same issue

**Comment by ayushi023** [comment]
Hi @tommycp96 
Is there any way to force disable the same, I am also facing the same issue
