### ISSUE TITLE
iOS system dialog on acquireToken() and signout()

### ISSUE THREAD

**Issue by WolfyUK** [stashenergy/react-native-msal#13]
The issue reported [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/844) has been raised by our client. The ability to set [prefersEphemeralWebBrowserSession](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html#/c:objc(cs)MSALWebviewParameters(py)prefersEphemeralWebBrowserSession) in MSAL should be configurable based upon the app's requirements. When set to `NO` on iOS 13+ this will prevent the dialog below from being shown.

![Simulator Screen Shot - iPhone 6 - 2020-05-27 at 11 09 45](https://user-images.githubusercontent.com/3224486/83007001-ee848200-a00a-11ea-8869-682d96182943.png)

I've been having a play with a solution to this in my fork, and will link a PR shortly. However, I am yet to find out what the potential implications are of setting this to `YES`. My tests so far using the example in this repo seem fine but if you want to close as 'by design' or reject the PR then that's fine!

> 👍🏼 Thanks for putting in the work to get this package out there after Auth was removed from App Center! It's been extremely beneficial to a WIP project.

**Comment by josmithua** [comment]
Thanks so much for the PR @WolfyUK! And thank you for the compliment, really appreciate it 😃

While I think that having the `prefersEphemeralWebBrowserSession` flag default to `NO` provides a nicer SSO experience with other apps and browsers, if your app is the only sign in point (as is the case of @stashenergy at this moment as well), this would be a nice setting to be able to configure.
