### ISSUE TITLE
Typescript return type mismatch in certain functions

### ISSUE THREAD

**Issue by k-mehta** [stashenergy/react-native-msal#131]
**Bug Description:**
The following functions can return null, but typescript signature claims that they cannot:
1. PublicClientApplication.getAccount
2. PublicClientApplication.acquireToken
3. PublicClientApplication.acquireTokenSilent

**Environment Information:**
 - `react-native-msal` version: 4.0.2
 - `react-native` version: 0.66.3

**Comment by josmithua** [comment]
The [typescript types](https://github.com/stashenergy/react-native-msal/blob/master/src/types.ts#L10-L31) do indeed indicate that these functions can possibly return `undefined`. Are you saying `undefined` should be replaced with `null`?

**Comment by k-mehta** [comment]
I have to admit, I don't know much about how to build libraries, so I don't know if this is a packaging issue. But this is what I'm seeing in `\node_modules\react-native-msal\build\publicClientApplication.d.ts`:

```
export declare class PublicClientApplication implements IPublicClientApplication {
    private readonly config;
    private _pca;
    constructor(config: MSALConfiguration);
    init(): Promise<this>;
    acquireToken(params: MSALInteractiveParams): Promise<MSALResult>;
    acquireTokenSilent(params: MSALSilentParams): Promise<MSALResult>;
    getAccounts(): Promise<MSALAccount[]>;
    getAccount(accountIdentifier: string): Promise<MSALAccount>;
    removeAccount(account: MSALAccount): Promise<boolean>;
    signOut(params: MSALSignoutParams): Promise<boolean>;
}
```

It appears that VS Code is getting type information from that file since that's what it navigates to when I click on **Go to definition** for any of those functions.

**Comment by josmithua** [comment]
Yeah it looks like TypeScript wasn't generating the return type based on the interface, but inferred from the class methods. I explicitly provided the return types which fixes things.
