### ISSUE TITLE
com.apple.AppSSO.AuthorizationError 

### ISSUE THREAD

**Issue by peddiarjun** [stashenergy/react-native-msal#132]
**Bug Description:**
Few of our users are receiving this MSAL error. As soon as the code calls the "acquireToken" , it immediately throws the following error and sign in fails. It doesn't even open the auth browser or authenticator app.

Error: Error Domain=NSURLErrorDomain Code=-1012 "(null)" UserInfo={NSErrorFailingURLStringKey=https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2Fmicrosoft.onmicrosoft.com%2Foauth2%2Fv2.0%2Fauthorize, NSErrorFailingURLKey=https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2Fmicrosoft.onmicrosoft.com%2Foauth2%2Fv2.0%2Fauthorize, _NSURLErrorRelatedURLSessionTaskErrorKey=(
"LocalDataTask <BBDFF055-C3FC-447A-985F-D9B4355F2A60>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <BBDFF055-C3FC-447A-985F-D9B4355F2A60>.<1>, MSALCorrelationIDKey=8C5BEED2-D931-4CAF-BD5A-B692C38E1FA5, NSUnderlyingError=0x280a7dad0 {Error Domain=kCFErrorDomainCFNetwork Code=-1012 "(null)" UserInfo={NSUnderlyingError=0x280a7d830 {Error Domain=com.apple.AppSSO.AuthorizationError Code=-9 "not AppSSO URL" UserInfo={NSLocalizedDescription=not AppSSO URL}}}}}

Error code: 1012
Error domain: com.apple.AppSSO.AuthorizationError
Error description: not AppSSO URL

**Steps To Reproduce:**
I am not able to repro on my iOS device but few of our users are facing this. like 300 sessions faced this in last 1 month and we have 50K user base.

**Expected Behavior:**
It should open the auth browser or authenticator to select an account.

**Environment Information:**
 - `react-native-msal` version: 4.0.2
 - `react-native` version: 0.63.3
 - Platform: iOS
 - Browser (if applicable): NA

**Additional Information:**

**Comment by josmithua** [comment]
Hi there, thanks for reporting this (I got your email too). Issues like this that happen 'randomly' and that can't be reproduced are really tricky to debug and fix. I really am not sure the best way to move forward.

This looks like it might be happening when the user uses "Sign In With Apple". Is this is the case?

**Comment by peddiarjun** [comment]
No, we don't have "Sign in with Apple", we are using Azure AAD login.
