### ISSUE TITLE
Not possible to update user claims [config] 

### ISSUE THREAD

**Issue by JNetrh** [stashenergy/react-native-msal#140]
I have:
- [x] Upgraded to the latest version of `react-native-msal`
- [x] Read the README thoroughly
- [x] Searched for similar issues
- [ ] Used breakpoint debugging in the Swift/Java module code
- [ ] Tried to reproduce the problem in the example app in this repository

**Problem description:**
aquireTokenSilet does not return updated claims. I went through the possibilities and discussions.  It seems that acquireTokenSilent does not return updated claims until the token expires. After that, a refresh token is used to obtain a new token and during this activity, the updated claims are fetched to the cache.

The msal describes other possibilities for how to update claims. Those are`ssoSilent`, `acquireTokenRedirect` or `acquireTokenPopup`. None of those is part of the library so I am stuck.

My way of thinking is to refresh the token by force before the token expires to update the claims. For that, I would need to know where does the library stores those data (refresh token).

my issue is clearly described in this short thread: https://githubmemory.com/repo/AzureAD/microsoft-authentication-library-for-js/issues/3639

The current workaround is to sign the user out each time the claims are updated.

**Relevant error messages and screenshots:**
Please provide error messages and screenshots here

**Environment Information:**
 - `react-native-msal` version: 4.0.3
 - `react-native` version: 0.66.1
 - Platform: Android, iOS

**Comment by josmithua** [comment]
`acquireTokenPopup` is what `acquireToken` uses on web.
