### ISSUE TITLE
authority not supported

### ISSUE THREAD

**Issue by mohamedanwer123** [stashenergy/react-native-msal#141]
when add authority props to confing object give this error 

 Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Non Microsoft authority is not supported yet in MSAL, MSALInternalErrorCodeKey=-42008}

```js
const pca = new PublicClientApplication({
  auth:{
    clientId: "my client id,
    redirectUri: my redirect id',	
    authority:'https://digitalrootsb2c.b2clogin.com/tfp/digitalrootsb2c.onmicrosoft.com',
    knownAuthorities:['B2C_1_reservation_signupsignin'],
  }
})
```

**Comment by josmithua** [comment]
Known authorities needs to be set to {authority}/{policy}

**Comment by mohamedanwer123** [comment]
@josmithua thank you it work fine now , but i got error when cancel or close login webview model in ios 

Error Domain=MSALErrorDomain Code=-50005 "(null)" UserInfo={MSALErrorDescriptionKey=User cancelled the authorization session., MSALCorrelationIDKey=CD669D21-7617-4CAE-8E22-DCDF3348AE98}

**Comment by josmithua** [comment]
Yes, you need to surround your call to acquireToken in a try-catch and handle the error how you would like.

**Comment by josmithua** [comment]
You can take a look at the B2CClient class in the example code which helps handle B2C scenarios: https://github.com/stashenergy/react-native-msal/blob/master/example/src/b2cClient.ts

**Comment by mohamedanwer123** [comment]
@josmithua  i'm  really surrounded the code in try-catch 

 onPress={async ()=>{
        const pca = new PublicClientApplication(B2C_SIGNIN_SIGNUP_CONFIG)
        try {
          const init = await pca.init()
          console.log('INIT   ', init)
          const res  = await pca.acquireToken({scopes: B2C_SCOPES});
          console.log('RES   ', res)
          setAccount(res.account)
        } catch (error) {
          console.error('TOKEN ERROR', error)
        }        
 }}
 
 but the error still show

**Comment by josmithua** [comment]
using `console.error` will show the error on screen. 

If you don't want to do anything when the user cancels log in, you can do something like:

```ts
try {
  // call to acquireToken
} catch (error) {
  if (!error.message.includes("User cancelled") {
	// handle all errors except those caused by user canceling login
  }
}
```

**Comment by mohamedanwer123** [comment]
@josmithua when i'am removed the console.log the error is hidden 

**thank you a lot**
