### ISSUE TITLE
How to force disable calling broker app on iOS? Getting an error MSALErrorDescriptionKey=application did not receive response from broker

### ISSUE THREAD

**Issue by ayushi023** [stashenergy/react-native-msal#142]
**Bug Description:**
Hope everything is fine, at first I would like to take the opportunity to appreciate this library is really nice!
But may need some of your guides and advice on how can we disable it to automatically call the broker app(if it's installed) on iOS?
With authenticator app I am not able to get token and getting an error  Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=application did not receive response from broker., MSALInternalErrorCodeKey=-42700, MSALCorrelationIDKey=7D46A125-708E-44E2-8B78-1F2852CFD111}
0

Could you please help I am stuck with the same?

**Comment by paulyiu-gammon** [comment]
is disable calling broker mean not use authenticator:sweat_smile:?

I add below code to AppDelegate.m to turn it off
```
MSALGlobalConfig.brokerAvailability = MSALBrokeredAvailabilityNone;
```
https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALGlobalConfig.html#:~:text=MSALBrokeredAvailabilityNone

**Comment by Drzaln** [comment]
hi @ayushi023 did you find any workaround for this?

**Comment by Drzaln** [comment]
hi @paulyiu-gammon in which line i can puth this code? I'm new with obj c programming

**Comment by josmithua** [comment]
@Drzaln, if you have an `ios` folder in your project, find the `AppDelegate.m` file, and find the method that has the signature:

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
```

Put the following line anywhere in the method before the `return` (just don't put it in an if-statement):

```objc
MSALGlobalConfig.brokerAvailability = MSALBrokeredAvailabilityNone;
```

If you are using Expo and don't have an AppDelegate, then unfortunately you can't do this unless you make an Expo config plugin.

I plan to add this feature to this library soon though. The Android equivalent is the `config.androidConfigOptions.broker_redirect_uri_registered` option, which is already supported.

**Comment by Drzaln** [comment]
@josmithua Ah thanks, I already put it in the correct line
