### ISSUE TITLE
[config] How can I programmatically close the MSAL webview?

### ISSUE THREAD

**Issue by jvgeee** [stashenergy/react-native-msal#146]
I have:
- [ x] Upgraded to the latest version of `react-native-msal`
- [ x] Read the README thoroughly
- [ x] Searched for similar issues
- [ NA] Used breakpoint debugging in the Swift/Java module code
- [ NA] Tried to reproduce the problem in the example app in this repository

**Problem description:**
My app's signup page has a "Log in" button. When pressed, it opens MSAL's login view via `await pca.acquireToken()`.

On that login page, I have a button at the bottom which says "Not a member? Sign up"

When the user clicks this button, I want to close the MSAL webview and return to the app. I'm currently sending the app a deeplink from this button, which is working correctly. However, I have no way to trigger the msal window to close and session to end.

I've tried putting the MSAL login trigger in a modal / in an empty component, but then I get

`[Error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Only one interactive session is allowed at a time., MSALInternalErrorCodeKey=-42402, MSALCorrelationIDKey=DB47838E-BC3E-4E1F-A634-96A214839E03}]`

Is this possible to do? How can I successfully cancel the `acquireToken` window?

**Comment by josmithua** [comment]
There is a cancel method [cancelCurrentWebAuthSession](https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALPublicClientApplication.html#/c:objc(cs)MSALPublicClientApplication(cm)cancelCurrentWebAuthSession) On the Native code but it's currently not exposed to  JavaScript

**Comment by josmithua** [comment]
Upon looking, there doesn't seem to be an Android equivalent, so I am hesitant to expose it to React Native. 

As far as I know the recommended/easiest process is to have the sign up flow in the same web authentication session
