### ISSUE TITLE
error TypeError: Cannot read property 'acquireToken' of undefined

### ISSUE THREAD

**Issue by gauravsbagul** [stashenergy/react-native-msal#15]
Hello,
I am having this issue `error TypeError: Cannot read property 'acquireToken' of undefined` i am trying this on IOS, Xcode 11, target os 10.0
please help

**Comment by josmithua** [comment]
Looks like the client is not defined. Did you create it with `new MSALClient(clientId)`? Please post your relevant code.

**Comment by josmithua** [comment]
I'm going to close this for now. Please comment if you have further issues.
