### ISSUE TITLE
Android release build is not working 

### ISSUE THREAD

**Issue by UpasnaGandhi** [stashenergy/react-native-msal#150]
MSAL configuration work very well on debug mode. But, when I am trying to run with release mode. It throws following error:

 ```
 java.lang.RuntimeException: Could not invoke RNMSAL.createPublicClientApplication
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source:192)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source:21)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source:0)
        at android.os.Looper.loop(Looper.java:223)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run
        
```
My msal_Config.json
```
{
  "client_id": "My_client-id",
  "authorization_user_agent": "DEFAULT",
  "redirect_uri": "msauth://com.myPackegeName/M74kWwKnLGHKWweswsUc5csggBRxjM%3D",
  "account_mode": "MULTIPLE",
  "broker_redirect_uri_registered": false,
  "authorities" : [
    {
      "type": "B2C",
      "authority_url": "https://domain.b2clogin.com/tfp/compnay.onmicrosoft.com/",
      "default": true
    }
  ]

}
```
Can you help me in configuration, for production mode?
Do I need to register new app on Azure for Production build?

**Environment Information:**
 - `react-native-msal` version: 3.1.1
 - `react-native` version: 6.3.1
 - Platform: Android

**Comment by josmithua** [comment]
You probably need to a different signature hash for your production build

**Comment by josmithua** [comment]
You may need to tweak your proguard settings. This SO post may help: https://stackoverflow.com/questions/52255786/java-lang-runtimeexception-could-not-invoke-rngooglefit-authorize

**Comment by UpasnaGandhi** [comment]
Thanks for the response. I got this resolved. My msal library wasn’t updated to recent update. I was using 3.1.1 for some random reason and when I update it and fixed other building issues. Its not building properly. 

Summary: 
Updated the react-native-msal library to latest version. Thanks
