### ISSUE TITLE
Can't Build Android with EAS Build at Expo

### ISSUE THREAD

**Issue by mrtry** [stashenergy/react-native-msal#151]
**Bug Description:**
Can't Build Android with EAS Build at Expo

**Steps To Reproduce:**

Do EAS Build

```
$ expo run:android -d
```

**Expected Behavior:**
Can Build Android with EAS Build at Expo

```
> Task :app:checkDebugAarMetadata FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.microsoft.device.display:display-mask:0.3.0.
     Searched in the following locations:
       - file:/Users/syamamoto/.m2/repository/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
       - file:/Users/syamamoto/Program/react-native-msal/example/node_modules/react-native/android/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
       - file:/Users/syamamoto/Program/react-native-msal/example/node_modules/jsc-android/dist/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
       - https://dl.google.com/dl/android/maven2/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
       - https://jcenter.bintray.com/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
       - https://www.jitpack.io/com/microsoft/device/display/display-mask/0.3.0/display-mask-0.3.0.pom
     Required by:
         project :app > project :reactnativemsal > com.microsoft.identity.client:msal:2.2.3 > com.microsoft.identity:common:3.6.7
```

**Environment Information:**
 - `react-native-msal` version 4.0.4:
 - `react-native` version: 0.64.3 (Expo 44)
 - Platform: Android
 
**Additional Information:**

It works if you set up a link to the Maven repository as shown in the setup of this repository
But Expo can't edit build.gradle by itself, so I can't set it.

I think I can solve this problem by setting link to Maven repository in build.gradle or Expo config plugins.
I thought I'd look into it and send out a PR, but I'll report it anyway.
Thanks for the good library!

**Comment by josmithua** [comment]
Hi there! Could you run `expo prebuild --platform android --clean --no-install` and then paste the contents of your `android/build.gradle` please? Or just let me know if you have the following line at the bottom of your file:

```
allprojects { repositories { maven { url "https://pkgs.dev.azure.com/MicrosoftDeviceSDK/DuoSDK-Public/_packaging/Duo-SDK-Feed/maven/v1" } } }
```

**Comment by mrtry** [comment]
Thanks for the reply.

I've already confirmed that it works after adding the maven repository to gradle.
I also had to add BrowserTabActivity to AndroidManifest.

Looking at the [Setup for Expo](https://github.com/stashenergy/react-native-msal/blob/master/docs/expo_setup.md), I thought these would be taken care of automatically.

**Comment by mrtry** [comment]
Sorry.
I must have made a setup mistake somewhere.
The Expo Plugin was working properly and did the whole setup.
I will close it.

The Expo Plugin is a good reference for when I make my own.
Thank you!
