### ISSUE TITLE
acquireToken never returns in Android app

### ISSUE THREAD

**Issue by troymdowd** [stashenergy/react-native-msal#19]
I was able to get the Android example app working by editing the `msal_config.json`, `AndroidManifest.xml`, `App.tsx`.  I had to change the existing encoded values based on my own `debug.keystore`.  It took a few tries to get the right values, but it worked eventually. _The **Example** section steps could be updated a little to be more clear._  

We previously had `react-native-app-auth` working via OAuth2 but we are refactoring to use MSAL.  I implemented everything in my own app as close to the same way as the working example app as I can.  

- Redirect URLs are correct in Azure and the app.
- Android Setup: Using MSAL steps 2 and 3 are complete and match the example, but with the correct package name/signature (see below)
- Android Setup: Using MSAL step 1 is unclear.  I've tried with and without the dependencies and maven code in one or both of my build.grade files. After trying every combination, I found that the `react-native-msal` package already contains the dependency.  These settings are not set in the example app.  _Is this necessary?_ 

When I call `msalClient.acquireToken()`, the screen flashes and nothing happens.  No more code runs after that point.  It seems to be stuck waiting for the browser window to open to the login screen, but it never opens.  I traced the calls side by side between the example app and mine and they both do the exact same thing all the way until the example app opens the browser window.  _Is there some place that blocks opening new browser tabs?_

I don't see any errors in logcat, and nothing is caught. 

**msal_config.json** 
```
{
  "client_id" : "<my_client_id>",
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "msauth://com.EmployeeApp/<my_base64_html_encoded_signature>",
  "account_mode": "MULTIPLE",
  "authorities" : [
    {
      "type": "AAD",
      "authority_url": "https://login.microsoftonline.com/common"
    }
  ]
}

```

**AndroidManifest.xml**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.EmployeeApp">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.microsoft.identity.client.BrowserTabActivity">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
                android:scheme="msauth"
                android:host="com.EmployeeApp"
                android:path="/{my_base64_package_signature}" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**AuthHelper.js Higher order component**
```
import MSALCLient from 'react-native-msal';
import AsyncStorage from '@react-native-community/async-storage';

export const AuthConfig = {
  clientId: '<my_client_id>',
  scopes: [
    'openid',
    'offline_access',
    'profile',
    'user.read',
    'calendars.read',
    'Sites.ReadWrite.All',
    'Calendars.Read.Shared',
  ],
  sisuAuthority: 'https://login.microsoftonline.com/common',
};

const handleResult = async result => {
  //save the result to persistant storage.
  // Store the access token, refresh token, and expiration time in storage
  console.log(result);
  await AsyncStorage.setItem('userToken', result.idToken);
  await AsyncStorage.setItem('refreshToken', result.accessToken);
  await AsyncStorage.setItem('expireTime', result.expiresOn);
};

const msalClient = new MSALCLient(AuthConfig.clientId);

const acquireToken = async () => {
  try {
    console.info('Begin token acquisition.');
    const res = await msalClient.acquireToken({
      authority: AuthConfig.sisuAuthority,
      scopes: AuthConfig.scopes,
    });
    handleResult(res);
  } catch (error) {
    console.warn(error);
  }
};

export const signInAsync = async () => {
  //check to see if the user already has a token
  const userToken = await AsyncStorage.getItem('userToken');
  if (userToken) {
    console.log(userToken);
    return; //token exists, so bail out
  }
  //no token, so log the user in
  await acquireToken();
};

export const signOutAsync = async () => {
  //TODO: Implement msalClient.removeAccount()

  // Clear storage
  await AsyncStorage.removeItem('userToken');
  await AsyncStorage.removeItem('refreshToken');
  await AsyncStorage.removeItem('expireTime');
};
```

**Comment by josmithua** [comment]
Hi @troymdowd, I noticed that they updated the "Using MSAL" section of the Android: Step 1 is **not** required to implement this library into your app. The dependency is already declared in the library's gradle file. I will update the README.

If you did add `implementation 'com.microsoft.identity.client:msal:1.5.+'`, please remove it and try again. Version 1.5.x doesn't work with with this library yet, and may be the reason the call to `acquireToken` is failing.

**Comment by troymdowd** [comment]
I think that was it.  I cleaned up the build files and it is working as expected.  Thanks.
