### ISSUE TITLE
Is this library support multiple accountmode

### ISSUE THREAD

**Issue by Shing-Ho** [stashenergy/react-native-msal#2]
Is this library support multiple accountmode?
I am getting the issue about "AccountMode in configuration is not set to multiple Cannot initialize multiple account PublieClientApplication."

**Comment by josmithua** [comment]
Hi @Shing-Ho, is this happening on Android? If so, do you have `"account_mode": "MULTIPLE"` in your `msal_config.json`?

**Comment by Shing-Ho** [comment]
I tried, "account_mode": "MULTIPLE" after that I can see the BrowserTabActivitity is missing error. After some googling I changed the android_host. Then after that I couldn't open app. After open app it closed immediately.

**Comment by josmithua** [comment]
Does your app quit regardless of whether you call a method in this library? Is there an error thrown?

**Comment by Shing-Ho** [comment]
It's quitting when I openning app

**Comment by josmithua** [comment]
If you remove all calls to the react-native-msal API does the problem still persist? Can you share your code?

**Comment by Shing-Ho** [comment]
Currently, I am contacting with Microsoft dynamic support team. I think I need to solve problem in azure directory first. And I've already uninstall it because can't develop other features. I will install again later once I solved the problem with azure directory

**Comment by josmithua** [comment]
I am going to close this then. 

If you have resolved all other problems and still have an issue with this library, feel free to open another issue.

**Comment by Doorbell-team** [comment]
Hi, I'm getting the same error.

**Comment by JustineAyroor** [comment]
same here
