### ISSUE TITLE
null is not an object (evaluating 'RNMSAL.acquireToken')

### ISSUE THREAD

**Issue by JustineAyroor** [stashenergy/react-native-msal#20]
I am using this package with the mobile app built on expo 
the MSALClient gets instantiated but I cannot use this which gives me the error mentioned below
can someone please tell me what is the error about and how to resolve this issue??
Is expo responsible for this kind of error ?? 

null is not an object (evaluating 'RNMSAL.acquireToken')
- node_modules/react-native-msal/src/index.tsx:67:80 in MSALClient#acquireToken
* App.js:60:23 in acquireToken
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:271:30 in invoke
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:135:28 in invoke
- node_modules/regenerator-runtime/runtime.js:170:17 in Promise$argument_0
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
- node_modules/regenerator-runtime/runtime.js:169:27 in Promise$argument_0
- node_modules/regenerator-runtime/runtime.js:192:38 in enqueue
- node_modules/regenerator-runtime/runtime.js:216:8 in exports.async
* App.js:60:23 in acquireToken
- node_modules/react-native/Libraries/Components/Touchable/TouchableNativeFeedback.android.js:229:45 in createReactClass$argument_0.touchableHandlePress
* [native code]:null in touchableHandlePress
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:880:34 in TouchableMixin._performSideEffectsForTransition
* [native code]:null in _performSideEffectsForTransition
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:779:44 in TouchableMixin._receiveSignal
* [native code]:null in _receiveSignal
- node_modules/react-native/Libraries/Components/Touchable/Touchable.js:490:24 in TouchableMixin.touchableHandleResponderRelease
* [native code]:null in touchableHandleResponderRelease
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:307:15 in invokeGuardedCallbackImpl
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:531:36 in invokeGuardedCallback
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:555:30 in invokeGuardedCallbackAndCatchFirstError
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:722:42 in executeDispatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:744:20 in executeDispatchesInOrder
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:907:29 in executeDispatchesAndRelease
* [native code]:null in forEach
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:887:16 in forEachAccumulated
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:932:21 in runEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:1096:19 in runExtractedPluginEventsInBatch
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2796:6 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:18791:14 in batchedUpdates$1
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2709:30 in batchedUpdates
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2794:17 in batchedUpdates$argument_0
- node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js:2870:28 in receiveTouches
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:436:47 in __callFunction
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:111:26 in __guard$argument_0
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:384:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:110:17 in __guard$argument_0
* [n

**Comment by josmithua** [comment]
I have not tested this library with expo but it should work (although not on web). I'm not sure what to tell you but to check that everything is wired up correctly.

**Comment by WolfyUK** [comment]
We have it working fine on a bare Expo app. Which Expo workflow are you using, @JustineAyroor ?

**Comment by JustineAyroor** [comment]
> We have it working fine on a bare Expo app. Which Expo workflow are you using, @JustineAyroor ?

Im using the Managed Workflow @WolfyUK 
So I have to eject and then try the library -- Right ??

**Comment by WolfyUK** [comment]
@JustineAyroor Yes, that is correct. Or begin with one of the bare workflow templates.

**Comment by JustineAyroor** [comment]
Hi thanks the bare workflow worked on IOS but not on android .... will be opening another issue for that .... Appreciate your help on this
