### ISSUE TITLE
AccountMode is not set to Multiple?  

### ISSUE THREAD

**Issue by JustineAyroor** [stashenergy/react-native-msal#23]
![image](https://user-images.githubusercontent.com/25484899/88497462-6c72f400-cf8e-11ea-8c3b-ed7469ca6a51.png)

So I converted my app to a bare workflow and everything works good on IOS but on android I get an error mentioned in the above screenshot
react-native version = 0.61

I made the changes in the Android Manifest and also followed Step 1 to 3 of the 'Using Msal' link attacted in the documentation.
I also tried to change the contents in the intent filter as prescribed by other resources I came across but it still keeps complaining with the same error on Android.

Is this because I am using a single tenant registration on Azure. if so Why does it work for IOS ?
Am I missing some other configurations in my build.gradle file? or any other configurations ?
If anyone has come across the same issue with this package please post your comments/solutions to resolve this.
Thanks
Justine A

**Comment by JustineAyroor** [comment]
This is the config in my assets folder
{
    "client_id" : "Client id ",
    "authorization_user_agent" : "DEFAULT",
    "redirect_uri" : "msauth://package name/<some code>",
    "broker_redirect_uri_registered": true,
    "authorities" : [
      {
        "type": "AAD",
        "authority_url": "https://login.microsoftonline.com/<tenant_id>"
      }
    ]
  }

and this is the code added on AndroidManifest.xml 

<activity
        android:name="com.microsoft.identity.client.BrowserTabActivity">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
                android:scheme="msauth"
                android:host="<my package name>"
                android:path="/<something i got from azure portal>" />
            
        </intent-filter>
    </activity>

**Comment by JustineAyroor** [comment]
For your reference.
Code in my AndroidManifest.xml File
```
<activity
        android:name="com.microsoft.identity.client.BrowserTabActivity">
        <intent-filter>
            <action android:name="android.intent.action.VIEW" />
            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />
            <data
                android:scheme="msauth"
                android:host="<My package name>"
                android:path="/<something i got from the azure portal>" />
            
        </intent-filter>
</activity>
```
msal_config.json file in the assets folder

{
    "client_id" : "<My client ID>",
    "authorization_user_agent" : "DEFAULT",
    "redirect_uri" : "msauth://<package name for android>/<something  i got from the azure portal>",
    "broker_redirect_uri_registered": true,
    "authorities" : [
      {
        "type": "AAD",
        "authority_url": "https://login.microsoftonline.com/<tenant id>"
      }
    ]
  }

**Comment by Maddumage** [comment]
I had the same issue but after adding "account_mode": "MULTIPLE" to the msal_config.json file the error fixed and another error occurred which indicates that Manifest.xml does not define the BrowserTabActivity for the MSAL. Please let us know if this is a library issue or another.

**Comment by josmithua** [comment]
I don't see `"account_mode": "MULTIPLE"` in your `msal_config.json`

See https://github.com/stashenergy/react-native-msal/issues/2#issuecomment-592209261

**Comment by JustineAyroor** [comment]
Hi @josmithua i added that to my msal_config but now im getting the an error called BrowserTabActivity is Missing.
I have this specified inside the intent-filter of my AndroidManifest.xml file
What do you think is the problem ? 
has anyone got a solution for this 
Thanks

**Comment by JustineAyroor** [comment]
Does it have to be MULTIPLE ?? When I change it to SINGLE it gives me the same error as shown in the screenshot i posted earlier
```
{
    "client_id" : "<client id>",
    "authorization_user_agent" : "DEFAULT",
    "redirect_uri" : "msauth://<package name>/<hash>",
    "broker_redirect_uri_registered": true,
    "account_mode": "SINGLE",
    "authorities" : [
      {
        "type": "AAD",
        "authority_url": "https://login.microsoftonline.com/<tenant_id>"
      }
    ]
  }
```

**Comment by JustineAyroor** [comment]
> Hi @josmithua i added that to my msal_config but now im getting the an error called BrowserTabActivity is Missing.
> I have this specified inside the intent-filter of my AndroidManifest.xml file
> What do you think is the problem ?
> has anyone got a solution for this
> Thanks

To solve this check if you have the correct signature hash in the intent-filter of your AndroidManifest.xml 

https://stackoverflow.com/questions/57353879/error-intent-filter-for-browsertabactivity-is-missing-while-using-azuread-ms

I used the base64 URL encoded signature hash which is why it was complaining about the BrowserTabActivity. 

However, after making these changes i ran into a redirect_uri mismatch,
I just pasted the same redirect_uri provided to me by Azure into the config file.
Im not sure what could be the issue is here.

![image](https://user-images.githubusercontent.com/25484899/88576449-7985f680-d013-11ea-9d89-622144cd669a.png)

Please do let me know if anyone has a solution.
Thanks

**Comment by josmithua** [comment]
> Does it have to be MULTIPLE ?? When I change it to SINGLE it gives me the same error as shown in the screenshot i posted earlier

Yes, it has to be `MULTIPLE`.
