### ISSUE TITLE
Storing Token 

### ISSUE THREAD

**Issue by kayvanhaverbeck** [stashenergy/react-native-msal#25]
What is the proper way to check if the user has already signed in when opening the app. 

Use Case: 
1. User signs in and retrieves access_token. 
2. Closes the Application
3. Retrieve previously obtained access_token. 

Does the plugin handle this?

**Comment by josmithua** [comment]
This module does not handle storing the token, but the native MSAL libraries do–in a sense. All you need to do is persist the account identifier returned in the result. Then provide that to `acquireTokenSilent`. It will return the same (previous) access token if it is still valid, or return a new one if the previous token has expired. This way you do not have to check the expiry date yourself. 

You can persist the account identifier easily using [Async Storage](https://github.com/react-native-community/async-storage) or whatever other persistent storage solution you have at your disposal.

**Comment by josmithua** [comment]
This is similar to what I have in my app:

```js
  public getAccessToken = async () => {
    const accountIdentifier = await retrieveAccountIdentifier();
    if (accountIdentifier === null) {
      const authResult = await this.msalClient.acquireToken({
        authority: this.sisuAuth,
        scopes: this.scopes,
      });
      await storeAccountIdentifier(authResult.account.identifier);
      return authResult.accessToken;
    } else {
      const authResult = await this.msalClient.acquireTokenSilent({
        authority: this.sisuAuth,
        scopes: this.scopes,
        accountIdentifier: accountIdentifier,
      });
      return authResult.accessToken;
  };

**Comment by josmithua** [comment]
If you need any more guidance let me know!
