### ISSUE TITLE
[TypeError: null is not an object (evaluating 'RNMSAL.acquireToken')]

### ISSUE THREAD

**Issue by genesisemmloh** [stashenergy/react-native-msal#27]
after following all the instructions as a recepy, very new as 3 days on React Native.
> npm install react-native-msal
> register the app on azure.
> i have a proper workflow for login.
> run the keytool  to get the signature hash(i was ask for the password).
> modify the msal_config.json and set the Redirect URIs on Azure app.

this is how i use it:

const msalClient = new MSALClient(msalApp.auth.clientId);
  async onSignIn(redirect: boolean) {                
            try {
  
                const result = await msalClient.acquireToken({
                    authority: msalApp.auth.authority,
                    scopes:tokenRequest.scopes,  
                  }); 
                  
            } catch (error) {
                console.log('error');
                console.log(error);
            }  
        }

i run this react native app on an emulator with npm run android .... 
does this should work as testing it on my local ? or needs to be packed and published?
greetings.
sincerely emmanuel.

**Comment by josmithua** [comment]
Hi there! Welcome to React Native, and thanks for using this library!

You should be able to test locally. 

Did you update your AndroidManifest.xml with the correct values?

**Comment by genesisemmloh** [comment]
> Hi there! Welcome to React Native, and thanks for using this library!
> 
> You should be able to test locally.
> 
> Did you update your AndroidManifest.xml with the correct values?

do mean regarding the package name, that should be the same as in the Azure URI registration?
i copy that info from azure, i can see the only diff its account_mode value, but the rest its all same
![image](https://user-images.githubusercontent.com/53597236/89618309-2110ed80-d88c-11ea-9026-807d8719867a.png)

**Comment by genesisemmloh** [comment]
Last Update: yes i have check the  AndroidManifest.xml again.
i notice another section here called activity... which i dont have..
so i have added this 
<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="msauth" android:host="com.bm_loacker_handel" android:path="/{hash}" />
      </intent-filter>
    </activity>

then i needed to clean the gradle...

and i think im spet further now.

![image](https://user-images.githubusercontent.com/53597236/89622933-19554700-d894-11ea-886e-59ed5d953a90.png)

**Comment by josmithua** [comment]
Hi Emmanuel, looks like you got it working on the react-native side, that's great.

This link might help you register your application: https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-register-applications?tabs=app-reg-ga

I believe the only scope you actually need is `user_impersonation`.

**Comment by josmithua** [comment]
I will close this now. If you run in to any other issues with this library feel free to open another issue.

Cheers!

**Comment by genesisemmloh** [comment]
Yes , thank you  @josmithua , i belive my error is that i have register my app in Azure B2C... and it seams this only works for azure apps. do you have any idea? see you later

**Comment by josmithua** [comment]
This library works for both Common and B2C apps

**Comment by genesisemmloh** [comment]
> This library works for both Common and B2C apps

Do you know how to register the App in B2C? it seams it a different process.

**Comment by josmithua** [comment]
The link I gave you above is for B2C applications. What are you having trouble with specifically?

**Comment by genesisemmloh** [comment]
Well the info you passt me was to register a web app.
mine error still "The provided application I'd it's not valid against the service".
How to register an app in B2C it's what I don't find anywhere.
Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by genesisemmloh** [comment]
i will give you some info i found to make this work...

**first** the registration of your Mobil App on Azure B2C will be like this: 
![image](https://user-images.githubusercontent.com/53597236/91824544-3a167f80-ec3b-11ea-9d40-6140f919d414.png)

followed by this documentation:
https://docs.microsoft.com/en-us/azure/active-directory-b2c/add-native-application?tabs=app-reg-ga

**second** the msal_configuration.json its also with different values. this ofcourse needs also changes on the AndroidManifest
![image](https://user-images.githubusercontent.com/53597236/91824915-cb85f180-ec3b-11ea-9092-ca0b5f04dd21.png)

**Comment by josmithua** [comment]
You need to click the "Add a platform" button under Platform Configurations in the portal, and add one for Android, and one for iOS/macOS

**Comment by genesisemmloh** [comment]
sorry, What you suggest me doesnt work on a B2C application.
just to make this clear, do you register your app like this? because this is the way to register a B2C app.

i would suggest you give it a try. and copy all my configurations i did, to replicate that **really there is an error on the aquireToken method.** i mena if you want this library supports B2C.

![image](https://user-images.githubusercontent.com/53597236/91941347-5f69c300-ecf9-11ea-972b-97f888ada41e.png)
if you try to add an adroid app on this B2C app you wiull get an error.
![image](https://user-images.githubusercontent.com/53597236/91941699-e880fa00-ecf9-11ea-825f-050ecee2ff09.png)
