### ISSUE TITLE
Can we remove browser url preview?

### ISSUE THREAD

**Issue by Maddumage** [stashenergy/react-native-msal#28]
When loading the azure authentication page on the top of the page will display the URL data that related to the application. Can we remove this section? Is it possible?

**Comment by josmithua** [comment]
Hi there,

This is not possible. The url is displayed so that the user understands the context of the authentication session in which they are being asked to enter credentials and give consent.

Sorry I couldn't be of more help.

**Comment by Maddumage** [comment]
If it is about user consent, there have some applications that not display the URL, (Ex-Real [Madrid Club app](https://play.google.com/store/apps/details?id=com.mcentric.mcclient.MyMadrid&hl=en) use azure ad b2c and react native.) :(

**Comment by josmithua** [comment]
It’s considered bad practice. Also I still see it on iOS:

![0F35BCC7-8713-4725-A838-B282CE7F2075](https://user-images.githubusercontent.com/3375071/90567672-e60e9400-e180-11ea-8009-67ecfed9421b.png)
![E13DB5F1-3915-42A5-82B6-E070B034CC6F](https://user-images.githubusercontent.com/3375071/90567673-e6a72a80-e180-11ea-8c72-7bc94dae415e.png)

**Comment by Maddumage** [comment]
@josmithua Got it. :) Thank you very much.
