### ISSUE TITLE
IOS integration issue

### ISSUE THREAD

**Issue by sureshbakshi** [stashenergy/react-native-msal#29]
### Configurations using in my app

**XCode: 10.1**

**podfile:**

> platform :ios, '10.0'

**info.plist**

	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>com.myapp.app</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>msauth.myapp.app</string>
				<string>com.myapp.app</string>
			</array>
		</dict>
	</array>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>msauth</string>
		<string>msauthv2</string>
		<string>msauthv3</string>
	</array>

**appdelegate.m**

#import <MSAL/MSAL.h>
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
    return [MSALPublicClientApplication handleMSALResponse:url
                                         sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]];
}

**package.json**

`    "react-native-msal": "^2.0.3",
`

**keychain-access-groups**

> com.microsoft.adalcache

### **Error while running the app:**

![Screenshot 2020-08-13 at 5 42 54 PM](https://user-images.githubusercontent.com/19382918/90133314-df50dd00-dd8c-11ea-95b3-fa3efabfa20b.png)

**Comment by josmithua** [comment]
Hi Suresh,

You might need to upgrade to XCode 11, as I think those symbols were introduced in iOS 13.

**Comment by sureshbakshi** [comment]
Thanks @josmithua ,

After updating OS and Xcode i am able to run the application.
