### ISSUE TITLE
Cannot read property 'acquireToken' of undefined in Android

### ISSUE THREAD

**Issue by sureshbakshi** [stashenergy/react-native-msal#33]
When trying to acquire token . it is throwing "Cannot read property 'acquireToken' of undefined"

**Comment by sureshbakshi** [comment]
It seems it is not linked automatically. if anyone facing same issue try below approach. 

in MainApplication.java add

>  import com.reactnativemsal.RNMSALPackage;


in the package list add

>  new RNMSALPackage()

**Comment by josmithua** [comment]
What version of React Native are you using? You should not have to do this on React Native >=0.61

**Comment by sureshbakshi** [comment]
forgot to mention version : here is my version number "react-native": "0.60.5".
