### ISSUE TITLE
How to make webview normal in iOS instead of Popup like. 

### ISSUE THREAD

**Issue by ShubhamC78** [stashenergy/react-native-msal#36]
In Ios the Screen look like popup message. how to make it normal web view 
<img width="347" alt="Screenshot 2020-09-07 at 11 49 34 AM" src="https://user-images.githubusercontent.com/46701268/92355018-0cc94600-f101-11ea-909b-a64c218ac3b0.png">

**Comment by josmithua** [comment]
Hi there, this library currently does not expose the options to set the webview style. If this is something that is important to you, I can add it in the future.

**Comment by ShubhamC78** [comment]
> Hi there, this library currently does not expose the options to set the webview style. If this is something that is important to you, I can add it in the future.

Please add if it is possible

**Comment by josmithua** [comment]
I will plan to add it to the v3 release

**Comment by josmithua** [comment]
Hi @ShubhamC78, I have added the ability to set the presentation style of the webview in iOS in the latest beta version ([v3.0.0-beta.10](https://github.com/stashenergy/react-native-msal/tree/v3.0.0-beta.10)). However it only has an effect if you change the webview type. I don't recommend doing this, as by default MSAL will choose the best and most secure webview. See [this section of the source](https://github.com/stashenergy/react-native-msal/blob/v3.0.0-beta.10/src/types.ts#L75-L88) for more info.
