### ISSUE TITLE
acquireToken throw error long java.lang.Long.longValue()

### ISSUE THREAD

**Issue by genesisemmloh** [stashenergy/react-native-msal#37]
acquireToken error
[Error: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference]

**Comment by josmithua** [comment]
People are getting this error when their scopes are wrong. Please double check your scopes.

**Comment by genesisemmloh** [comment]
Hi thanks, yes i have seen it, under the Expose an API regiterd my sccope, but how should i use it?
should i use the complete url, like:
['https://genesiscloudapps.onmicrosoft.com/api/scone_name']
or just the 'scope_name'?
or how? for me its not working.

**Comment by genesisemmloh** [comment]
yes the Scope needs to be added on API Permissions section.
and the name should be entered complete. ex.
https://{tenantName}.onmicrosoft.com/api/{scopename}
thanks we can close this.
like commented before use my configurations if you want to set this with B2C 👍
