### ISSUE TITLE
Support for Single Account Configuration

### ISSUE THREAD

**Issue by kayvanhaverbeck** [stashenergy/react-native-msal#38]
Do you guys plan on supporting  ISingleAccountPublicClientApplication

I am currently getting the following error: 
com.microsoft.identity.client.exception.MsalClientException: AccountMode in configuration is not set to multiple. Cannot initialize multiple account PublicClientApplication.
        at com.microsoft.identity.client.PublicClientApplication.createMultipleAccountPublicClientApplication(PublicClientApplication.java:810)
        at com.microsoft.identity.client.PublicClientApplication.createMultipleAccountPublicClientApplication(PublicClientApplication.java:573)
        at com.reactnativemsal.RNMSALModule.<init>(RNMSALModule.kt:18)
        at com.reactnativemsal.RNMSALPackage.createNativeModules(RNMSALPackage.kt:12)
        at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
        at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
        at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
        at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
        at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1225)
        at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
        at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1016)
        at java.lang.Thread.run(Thread.java:764)

**Comment by josmithua** [comment]
Hi there, as you’ve seen we don’t support it currently, but I don’t think it’d be too hard to add. If you want to submit a PR feel free. Otherwise I will get to it when I can. Cheers!

**Comment by kayvanhaverbeck** [comment]
I was actually able to modify the code and it successfully compiled and authenticated: 

`package com.reactnativemsal

import android.util.Pair
import com.facebook.react.bridge.*
import com.microsoft.identity.client.*
import com.microsoft.identity.client.exception.MsalException
import java.io.File

class RNMSALModule(reactContext: ReactApplicationContext) : ReactContextBaseJavaModule(reactContext) {

    private val publicClientApplication: ISingleAccountPublicClientApplication

    init {
        val inputStream = reactApplicationContext.assets.open("msal_config.json")
        val file = File.createTempFile("RNMSAL_msal_config", ".tmp")
        file.deleteOnExit()
        FileUtils.copyInputStreamToFile(inputStream, file)
        publicClientApplication = PublicClientApplication.createSingleAccountPublicClientApplication(reactApplicationContext, file)
    }

    override fun getName(): String {
        return "RNMSAL"
    }

    @ReactMethod
    fun acquireToken(params: ReadableMap, promise: Promise) {
        try {
            // Required parameters
            val authority = params.getString("authority")!!
            val scopes = readableArrayToStringList(params.getArray("scopes")!!)

            // Optional parameters but supplied with default values, so don't have to check if null
            val promptType = params.getInt("promptType")
            val loginHint = params.getString("loginHint")!!
            val extraScopesToConsent = readableArrayToStringList(params.getArray("extraScopesToConsent")!!)
            val eqp = params.getMap("extraQueryParameters")!!
            val eqpHashMap = eqp.toHashMap()
            val extraQueryParameters = arrayListOf<Pair<String, String>>()
            for (o in eqpHashMap.entries) {
                val pair = Pair(o.key.toString(), o.value.toString())
                extraQueryParameters.add(pair)
            }

            val parameters = AcquireTokenParameters.Builder()
                    .startAuthorizationFromActivity(this.currentActivity)
                    .fromAuthority(authority)
                    .withScopes(scopes)
                    .withPrompt(Prompt.values()[promptType])
                    .withAuthorizationQueryStringParameters(extraQueryParameters)
                    .withLoginHint(loginHint)
                    .withOtherScopesToAuthorize(extraScopesToConsent)
                    .withCallback(getAuthInteractiveCallback(promise, authority))
                    .build()

            publicClientApplication.acquireToken(parameters)

        } catch (e: Exception) {
            promise.reject(e)
        }
    }

    private fun getAuthInteractiveCallback(promise: Promise, authority: String): AuthenticationCallback {
        return object : AuthenticationCallback {
            override fun onCancel() {
                promise.reject("userCancel", "userCancel")
            }

            override fun onSuccess(authenticationResult: IAuthenticationResult) {
                promise.resolve(msalResultToDictionary(authenticationResult, authority))
            }

            override fun onError(exception: MsalException) {
                promise.reject(exception)
            }
        }
    }


    @ReactMethod
    fun acquireTokenSilent(params: ReadableMap, promise: Promise) {
        try {
            // Required parameters
            val authority = params.getString("authority")!!
            val scopes = readableArrayToStringList(params.getArray("scopes")!!)
            val accountIdentifier = params.getString("accountIdentifier")!!
            var account : IAccount? = null
            // Optional values with default values
            val forceRefresh = params.getBoolean("forceRefresh")

            publicClientApplication.getCurrentAccountAsync(object : ISingleAccountPublicClientApplication.CurrentAccountCallback {
                override fun onAccountLoaded(activeAccount: IAccount?) {
                    account = activeAccount
                    promise.resolve(activeAccount)
                }

                override fun onAccountChanged(priorAccount: IAccount?, currentAccount: IAccount?) {
                    account = currentAccount
                    promise.resolve(currentAccount)
                }

                override fun onError(exception: MsalException) {
                    account = null
                    promise.reject(exception)
                }
            })

            val silentParams = AcquireTokenSilentParameters.Builder()
                    .fromAuthority(authority)
                    .forAccount(account)
                    .withScopes(scopes)
                    .withCallback(getAuthSilentCallback(promise, authority))
                    .forceRefresh(forceRefresh)
                    .build()

            publicClientApplication.acquireTokenSilentAsync(silentParams)

        } catch (e: Exception) {
            promise.reject(e)
        }
    }

    private fun getAuthSilentCallback(promise: Promise, authority: String): SilentAuthenticationCallback {
        return object : SilentAuthenticationCallback {
            override fun onSuccess(authenticationResult: IAuthenticationResult) {
                promise.resolve(msalResultToDictionary(authenticationResult, authority))
            }

            override fun onError(exception: MsalException) {
                promise.reject(exception)
            }
        }
    }

    @ReactMethod
    fun removeAccount(params: ReadableMap, promise: Promise) {
        try {
            // Required parameters
            val accountIdentifier = params.getString("accountIdentifier")!!

            publicClientApplication.getCurrentAccountAsync(object : ISingleAccountPublicClientApplication.CurrentAccountCallback {
                override fun onAccountLoaded(activeAccount: IAccount?) {
                    promise.resolve(activeAccount)
                }

                override fun onAccountChanged(priorAccount: IAccount?, currentAccount: IAccount?) {
                    promise.resolve(currentAccount)
                }

                override fun onError(exception: MsalException) {
                    promise.reject(exception)
                }
            })

            publicClientApplication.signOut(object : ISingleAccountPublicClientApplication.SignOutCallback {
                override fun onSignOut() {
                    promise.resolve(null)
                }

                override fun onError(exception: MsalException) {
                    promise.reject(exception)
                }
            })
        } catch (e: Exception) {
            promise.reject(e)
        }
    }

    private fun msalResultToDictionary(result: IAuthenticationResult, authority: String): WritableMap {
        val map = Arguments.createMap()
        map.putString("accessToken", result.accessToken)
        map.putString("expiresOn", String.format("%s", result.expiresOn.time))
        map.putString("idToken", result.account.idToken)
        map.putArray("scopes", Arguments.fromArray(result.scope))
        map.putString("authority", authority)
        map.putString("tenantId", result.tenantId)
        map.putMap("account", accountToDictionary(result.account))
        return map
    }

    private fun accountToDictionary(account: IAccount): WritableMap {
        val map = Arguments.createMap()
        map.putString("username", account.username)
        map.putString("identifier", account.id)
        return map
    }

    private fun readableArrayToStringList(readableArray: ReadableArray): List<String> {
        return readableArray.toArrayList().map { item -> item.toString() }
    }
}
`

**Comment by josmithua** [comment]
Yes, but that breaks the multiple account scenario :). We will need a solution that handles both.

**Comment by josmithua** [comment]
I looked into this a little bit, and I don't think we will support this (for now), for a couple of reasons:

1. This is an Android-only abstraction, and doesn't carry over to iOS or the web.
2. You can easily accomplish what the single account mode does by writing a javascript wrapper over the PublicClientApplication class in your app, that allows a sign-in only if there's not an existing account signed in.

If you have any questions or feedback let me know :)

**Comment by Deepak9811** [comment]
> 

can you please provide me code

**Comment by josmithua** [comment]
Hi Deepak, if you are having trouble please open a new issue or discussion. Thanks
