### ISSUE TITLE
IOS dont display login popup

### ISSUE THREAD

**Issue by genesisemmloh** [stashenergy/react-native-msal#40]
Hi @josmithua ,its me again. thanks for all provided help.
After succeed with the Android Version, now im facing an error for IOS.
**i have a reactnative app and i registerd on B2C
my app simple wont get the Login dialog and  i get an error**

i have followed the instructions and add a KeychainSharing, edited de info.plist 
what i see its to different documentations, i have tried with both ways and i get same error.
**Note: for Android the redirect format that worked was, msal<client-id>**
first i read this one;
[https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios](url)
but i have also tried with different URlScheme 
like mentioned here:
[https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-ios-swift-native-msal/microsoft-authentication-library-b2c-ios/](url)

which seams to be unknown.
<img width="1388" alt="ios Error" src="https://user-images.githubusercontent.com/53597236/94133225-b11ced80-fe60-11ea-9ad6-4b8ec1d4ba18.png">

could you help me figuring out whats missing? is this an 404?
 @ShubhamC78  do you see something i did wrong?

**Comment by tonyma** [comment]
Hi @genesisemmloh, have you been able to implement the react native with Azure B2C authentication with this library?

I am getting the following error:

`[Error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Authentication response received without expected accessToken, MSALInternalErrorCodeKey=-42008, MSALCorrelationIDKey=11284C69-44F0-4C10-AC48-A906531E0449}]` 

Are you able to help?

**Comment by genesisemmloh** [comment]
hi, yes it worked for me, after too much trouble specially with IOS.

the Authority URL: im using now the url with the tfp format.
https://<TENANT_NAME>.b2clogin.com/tfp/<TENANT_NAME>.onmicrosoft.com/<POLICY_NAME>

the RedirectUri format for IOS. and android different, so you need to add 2 plataforms on the Authentication menu in your app B2C registration.

android:msal[ClientId]://auth
IOS:msauth.[BundleId]://auth

, But definitely what i think change, was the Library im using on my React Native Project, after the update 3.0.1, so make me think something was wrong in there.

What Configured Permissions do you have on your app?
Did You defined an Scope?


one more thing, this link for IOS, uses the wrong RedirectUri.
https://docs.microsoft.com/en-us/samples/azure-samples/active-directory-b2c-ios-swift-native-msal/microsoft-authentication-library-b2c-ios/

**Comment by tonyma** [comment]
Hi @genesisemmloh , thanks for getting back to me.

Still not able to make it work yet.

For now I only configured and testing on ios. Do I also need to configure for android environment if I am now really running on Android?

Her is my repo: https://dev.azure.com/TonyMaPurple/PD/_git/ReactNative

**Comment by genesisemmloh** [comment]
Hi, can you confirm if you have those scopes and permissions on azure?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by tonyma** [comment]
Hi @genesisemmloh , here are the permission config on azure b2c

![image](https://user-images.githubusercontent.com/4219509/94877342-96b8c480-049d-11eb-9c92-1e9d2917c11f.png)

**Comment by josmithua** [comment]
Hi, please continue the conversation on the dedicated issue #46. Thanks!
