### ISSUE TITLE
version 3.0.0 ERROR: Unable to find a matching configuration of project :react-native-msal

### ISSUE THREAD

**Issue by genesisemmloh** [stashenergy/react-native-msal#41]
HI, i guess after all my ask for B2c you did some changes. well i followed them on the guide, but now

the library throws an error
**None of the consumable configurations have attributes**
 while running Gradle. on npm run android.
this seams to be a missing type... that the library doesn't 
maybe the types are not exported?

i didnt face this issue before with previous version of the library. **im not using expo project.**

see attachted error from gradle build
[log Error.txt](https://github.com/stashenergy/react-native-msal/files/5291433/log.Error.txt)

**Comment by josmithua** [comment]
Thanks for reporting this, I was able to reproduce the problem and I am looking into it.

**Comment by josmithua** [comment]
I've published v3.0.1 which should fix this error. Please install the latest version and report whether it works or not. Thanks!

**Comment by genesisemmloh** [comment]
hi, not tested yet the 3.0.1 version, but i have continue working with the IOS (3.0)version.

i have different errors:
if my Authorithy URL like :
https://<TENANT_NAME>.b2clogin.com/<TENANT_NAME>.onmicrosoft.com/B2C_1_SignUpSingInAADOnly

![image](https://user-images.githubusercontent.com/53597236/94447854-90c79880-01aa-11eb-987b-df592e09b3cb.png)

if i use Authorithy URL like :
'https://<TENANT_NAME>.b2clogin.com/**tfp**/<TENANT_NAME>.onmicrosoft.com
setIosEphemeralSess

_i have use msal in other react projects and setting validateAuthority to false was necessary, did you missed this parameter?
i found some comments around:_
![image](https://user-images.githubusercontent.com/53597236/94448204-eb60f480-01aa-11eb-8fc3-5b6b8f4fbae4.png)

**Comment by josmithua** [comment]
Please try https://<TENANT_NAME>.b2clogin.com/**tfp**/<TENANT_NAME>.onmicrosoft.com/<POLICY_NAME>.

You also need to include all your authorities in the `knownAuthorities` property of the config object, so they don't get validated.

**Comment by josmithua** [comment]
Also, for Android, that is the old configuration. Please click `Add Platform` in the portal, select Android, and follow the instructions in the [README](https://github.com/stashenergy/react-native-msal#android-setup)

**Comment by josmithua** [comment]
Also, if next time you could open a new issue instead of commenting on an unrelated issue, that would be greatly appreciated. It helps me and everyone keep track of issues better. Thank you!

**Comment by genesisemmloh** [comment]
Thanks @josmithua  the Build succed we 3.0.1 works!

**Comment by genesisemmloh** [comment]
No this, is not possible. The only solution that works its to add this version of Platafform
[cid:image001.png@01D695C5.50748DC0]

This is the real only B2c Redirect Uri That works, also your authority needs to go without tfp.

Mit freundlichen Grüßen / Kind regards

Emmanuel Lohora
Digitalisierung & Innovation

Loacker Recycling GmbH
Lustenauerstrasse 33 - 6840 Götzis / Austria

www.loacker.cc <http://www.loacker.cc/>

[cid:image002.png@01D695C5.50C9D9B0]<https://www.loacker.cc/>

Firmenbuchgericht Feldkirch. FN 482816z
UID: ATU 72992808
Geschäftsführer: Christian Loacker
Es gelten unsere  AGB / GTC<https://www.loacker.cc/downloads/>

Folge uns auf

[cid:image005.png@01D695C5.50C9D9B0]<https://www.facebook.com/LoackerRecycling> [cid:image006.png@01D695C5.50C9D9B0] <https://www.instagram.com/LoackerRecycling/>

**Comment by genesisemmloh** [comment]
works its to add this version of Platafform
[cid:image001.png@01D695C5.8106F0E0]

This is the real only B2c Redirect Uri That works, also your authority needs to go without tfp.

In other words, on my client I check the plattaform to set the required URL format.

private config: MSALConfiguration = {
      auth: {
        clientId: msalApp.auth.clientId,
        authority: Platform.OS === 'ios'?msalApp.auth.authorityBase:msalApp.auth.authorityBaseIOS,
        redirectUri: Platform.OS === 'ios'?msalApp.auth.redirectUri:msalApp.auth.redirectUriIOS,
        knownAuthorities: msalApp.auth.policies,
      },
      cache: {cacheLocation: 'localStorage'},
    };


Mit freundlichen Grüßen / Kind regards

Emmanuel Lohora
Digitalisierung & Innovation

Loacker Recycling GmbH
Lustenauerstrasse 33 - 6840 Götzis / Austria

www.loacker.cc <http://www.loacker.cc/>

[cid:image002.png@01D695C5.814B4CE0]<https://www.loacker.cc/>

Firmenbuchgericht Feldkirch. FN 482816z
UID: ATU 72992808
Geschäftsführer: Christian Loacker
Es gelten unsere  AGB / GTC<https://www.loacker.cc/downloads/>

Folge uns auf

[cid:image005.png@01D695C5.814B4CE0]<https://www.facebook.com/LoackerRecycling> [cid:image006.png@01D695C5.814B4CE0] <https://www.instagram.com/LoackerRecycling/>

**Comment by josmithua** [comment]
> ```
>     private config: MSALConfiguration = {
>       auth: {
>         clientId: msalApp.auth.clientId,
>         authority: Platform.OS === 'ios'?msalApp.auth.authorityBase:msalApp.auth.authorityBaseIOS,
>         redirectUri: Platform.OS === 'ios'?msalApp.auth.redirectUri:msalApp.auth.redirectUriIOS,
>         knownAuthorities: msalApp.auth.policies,
>       },
>       cache: {cacheLocation: 'localStorage'},
>     };
> ```

A few things:
1. `config.auth.authority` should be set to a full authority, not just the base. So you need the base AND the policy
1. `config.auth.knownAuthorities` should be an array of authorities, (including the authority set in `config.auth.authority`), not just policies (it's unclear from your code snippet what `msalApp.auth.policies` contains)
1. You should _not_ have to have a separate authority base url for iOS and Android.
1. Side note: Your platform check appears to be backwards.
1. Since you're working with B2C, you might want to look at the [B2CClient class](https://github.com/stashenergy/react-native-msal/blob/master/example/src/b2cClient.ts) I wrote that might be of help.

Anyways, your config should look like:
```
{
  auth: {
    clientId: "<client_id_guid>",
    authority: "<authority_base_url>/<default_policy_name>", // for example, sign-in-up
    knownAuthorities: [
      "<authority_base_url>/<default_policy_name>", // sign-in-up
      "<authority_base_url>/<another_policy_name>" // for example, reset password
    ]
  }
}
```
