### ISSUE TITLE
Unit test mock issue: Cannot read property 'createPublicClientApplication' of undefined

### ISSUE THREAD

**Issue by WolfyUK** [stashenergy/react-native-msal#45]
When executing a jest test run against a non-explicitly mocked instance of `react-native-msal` v3, after upgrading from v2, the following error is returned:

```bash
Test suite failed to run

    TypeError: Cannot read property 'createPublicClientApplication' of undefined

      48 |             },
      49 |         };
    > 50 |         this.publicClientApplication = new PublicClientApplication(config);
         |                                        ^
      51 |     }
      52 | 
      53 |     public async acquireToken(type: AuthorityType = "signInAuthority"): Promise<MSALResult> {

      at new PublicClientApplication (node_modules/react-native-msal/lib/commonjs/publicClientApplication.native.ts:14:12)
```

To resolve, a new file `react-native-msal.js` was added to the root `__mocks__` directory with the following content:

```js
export { MSALPromptType } from "react-native-msal";
const PublicClientApplication = jest.fn().mockImplementation(() => { return {}; });
export default PublicClientApplication;
```

Other implementers may want to include more stubbed items in the mock, but this was sufficient for me. Is it worth adding something to the docs to reflect this change?

**Comment by josmithua** [comment]
Thanks for pointing this out. I'll add something to the changelog. I'll probably add a testing section in the readme at some point as well.

**Comment by josmithua** [comment]
Changelog updated in https://github.com/stashenergy/react-native-msal/commit/776479a524da4c05c63ab1d0090fa9e50ec619cc
