### ISSUE TITLE
Getting warning and not able to sign in user by using example code in the repo

### ISSUE THREAD

**Issue by tonyma** [stashenergy/react-native-msal#46]
Hi I copied the example code and updated to my own Azure B2C config however getting this warning and not able to sign in the user.

Are you able to help?

[Error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Authentication response received without expected accessToken, MSALInternalErrorCodeKey=-42008, MSALCorrelationIDKey=F627AAA7-FBA1-4DCC-B31B-C7C9B6EE676E}]

Here is the config:

```
import type {B2CConfiguration} from './b2cClient';

export const b2cConfig: B2CConfiguration = {
  auth: {
    clientId: '9ef51a55-0d20-4195-86f3-2e8d051792ad',
    authorityBase:
      'https://climbstravab2c.b2clogin.com/tfp/climbstravab2c.onmicrosoft.com',
    policies: {
      signInSignUp: 'B2C_1_SignInAndSignUp',
      passwordReset: 'B2C_1_PasswordReset',
    },
  },
};

export const b2cScopes = [
  'https://climbstravab2c.onmicrosoft.com/api/user_impersonation',
];

```

**Comment by josmithua** [comment]
Hi, are you using the b2cScopes in your login request?

**Comment by tonyma** [comment]
I am using exactly the same with the example in the repo. the only changes are the configuration.

b2cScopes is used for signIn request:

` const handleSignInPress = async () => {
    try {
      const res = await b2cClient.signIn({scopes, webviewParameters});
      setAuthResult(res);
    } catch (error) {
      console.warn(error);
    }
  };`

**Comment by josmithua** [comment]
Hi @tonyma, I configured a brand new tenant in a brand new application today and ran into this issue. I guess they have changed some things in the Portal. Here's how to get it working:

1. Navigate to your tenant in the Azure Portal
1. On the left nav, click "Expose an API"
1. Create a new Application ID URI for your application
1. Click "Add a scope", fill in the details, and then click "Add scope"
1. On the left nav, click "API Permissions"
1. Click "Add a permission"
1. Click "APIs my organization uses"
1. Find and click your app name
1. Find and check your newly created scope
1. When finished, click "Add Permissions"
1. Click "Grant admin consent for <app name>"

Please try these steps and let me know if it worked!

**Comment by tonyma** [comment]
Big thanks @josmithua , it worked for me by following the steps. 
I can now continue to work on my project and you may close this issue ticket.

But a questions is, is there a way to make it work without configure an application ID URI as it is not couraged to a applicatio URI:

![image](https://user-images.githubusercontent.com/4219509/94878117-d5e81500-049f-11eb-83a7-d68d0b43fbc8.png)

**Comment by josmithua** [comment]
Glad I could help! 

I don't know how to make it work without configuring an Application ID URI. If I find out I will post here in the future. It's also possible that the Integration Assistant is wrong, as it is in preview, but I don't know enough to say.

**Comment by tonyma** [comment]
Hi @josmithua, figured out make the b2c working without creating URI.

- Go to "API permissions" on the left menu of the registered application in Azure B2C tenant

- Click "Add a permission"

- Select "APIs my orgnization uses"

- Select "b2c-extensions-app. Do not modify. Used by AADB2C for storing user data."

- Tick the "user_impersonation" under "Permissions"

- Add the permission and "Grant admin consent for the tenant"

- The scope URI will be "https://extensions.cpim.windows.net/user_impersonation"

Worked for me. Not sure if it's the right way to configure Azure B2C tenant.

-
