### ISSUE TITLE
TypeError: Cannot read property 'createPublicClientApplication' of undefined

### ISSUE THREAD

**Issue by sp0033212000** [stashenergy/react-native-msal#51]
I run my app through expo-cli, got this error.

Then I checked my NativeModules, the RNMSAL was missed.

How could I fix this problem?

**Comment by josmithua** [comment]
Did you do a pod install?

**Comment by sp0033212000** [comment]
No, I run app through expo client of simulator, should I eject the project?

**Comment by josmithua** [comment]
This library does not work with the managed expo workflow or the expo client, so yes you will have to eject and follow all the setup steps in the README.
