### ISSUE TITLE
MSAL Shared Device Mode

### ISSUE THREAD

**Issue by kayvanhaverbeck** [stashenergy/react-native-msal#52]
Do you guys support any of the MSAL Shared Device Mode features: 

such as:  deviceModeTextView.setText(mSingleAccountApp.isSharedDevice() ?"Shared" :"Non-Shared");

Do you guys support Graph APIs via MSAL?

**Comment by josmithua** [comment]
Hi there,

Yes, authenticating to the Microsoft Graph API will work fine.

There's currently no way of retrieving shared device info with this library. From what I can see there is no iOS equivalent to the Android `isSharedDevice` method.

**Comment by kayvanhaverbeck** [comment]
What is the correct way to add the graph api to the authentication?

**Comment by josmithua** [comment]
Microsoft has quite a bit of documentation on MSAL and using their graph APIs, please refer to it. Cheers
