### ISSUE TITLE
Upgrade issue from 2.0.3 to 3.0.0 - java.lang.string cannot be cast to com.facebook.react.bridge.readablenativemap

### ISSUE THREAD

**Issue by Maddumage** [stashenergy/react-native-msal#53]
I'm trying to update the package from my previous version 2.0.3 to the latest 3.x.x and after upgrading I got this error on android and also not working the app in iOS also. 
But when I revert the all changes app working fine for both platforms.
I have tried fresh install all packages also.

**Comment by josmithua** [comment]
You’ll need to provide more info. When is this happening? What call to this library are you making? What parameters are you passing the call?

**Comment by Maddumage** [comment]
When - occurred when running the application after adding the new version (3.0.1) react-native-msal.  
What call - Use B2C sample codes
What parameters - related to the project as mentioned in the documentation
I did some search regarding this issue and it may be the case incompatible library. I'm using react-native 0.63.3.
is that the case?

**Comment by Maddumage** [comment]
Solved with the new release.
