### ISSUE TITLE
Exception in HostFunction: Malformed calls from JS: field sizes are different

### ISSUE THREAD

**Issue by davidkdev** [stashenergy/react-native-msal#57]
Hello,

RNVersion: 0.63.4
react-native-msal: 3.0.2

I have a problem with the `msalClient.signOut` function. I get an error `Exception in HostFunction: Malformed calls from JS: field sizes are different`.

This is my callstack:

![image](https://user-images.githubusercontent.com/70204121/104300280-8fef1400-54c6-11eb-8961-047ae433a855.png)

This is the code: 

```
<Button
            color={'#000000'}
            mode={'contained'}
            onPress={() => handleLogout()}>
            {getAppText(appText, TechnicalName.logout)}
</Button>

    handleLogout: () => {
      dispatch(authSlice.actions.clearToken());
      dispatch(authSlice.actions.logOut());
      dispatch(authSlice.actions.clearAccount());
      dispatch(authSlice.actions.changeLogedIn(false));
    },
```

 ```
  logOut: (state) => {
      const msalClient = new MSALClient(getMSALConfiguration());
      if (state.account) {
        console.log(state.account);
        msalClient.signOut({ account: state.account });
      }
    },
```
Any ideas on how to fix this? Did anyone else run into this problem? The app crashed on iOS aswell, not only on an emulated android phone.

**Comment by josmithua** [comment]
Hi there,

I am not able to reproduce the problem in the example app that is included in this repo. 

A bit of research regarding this error indicates that it's common when working with redux. 

Could you try to reproduce the error in the example app to verify that it's a problem with this library?
