### ISSUE TITLE
Android Error: AADSTS900144: The request body must contain the following parameter: 'grant_type'.

### ISSUE THREAD

**Issue by michPhil** [stashenergy/react-native-msal#59]
When trying to log in using Microsoft SSO, it returns this error after I authenticate my Microsoft email & password account.

Error: AADSTS900144: The request body must contain the following parameter: 'grant_type'.

RN Version: 0.63.4
react-native-msal version: 3.0.2

Config settings: 
```
{
    "client_id" : <my_client_id>,
    "authorization_user_agent" : "DEFAULT",
    "redirect_uri" : <my_redirect_uri>,
    "account_mode": "MULTIPLE",
    "broker_redirect_uri_registered": false,
    "authorities" : [
      {
        "type": "AAD",
        "authority_url": "https://login.microsoftonline.com/common"
      }
    ]
} 
```

If I change my _broker_redirect_uri_registered_ to true, it returns me a different error whereby it says my redirect URI and hash key does not match the one I set in Azure portal.

**Comment by josmithua** [comment]
Hi, what platform its this happening on? Android/iOS/web?

**Comment by michPhil** [comment]
Hi @josmithua . It's happening on Android

**Comment by josmithua** [comment]
@michPhil did you resolve this issue? You might not have the correct scopes.
