### ISSUE TITLE
iOS Bug: UIViewController+Utils.h collides with other react-native libraries

### ISSUE THREAD

**Issue by ajzozakiewicz** [stashenergy/react-native-msal#60]
`UIViewController+Utils.h` shares references with other react-native npm modules. While this is not an issue for this library per say, it may be a good idea to rename this to something specific to `react-native-msal`.

My specific use case is that I am trying to run both `react-native-msal` and `react-native-navigation` in the same project. This causes build issues in xcode due to both libraries referencing `UIViewController+Utils.h`

**Comment by josmithua** [comment]
The files aren’t actually being used so I’ll just delete them if they’re causing problems

**Comment by ajzozakiewicz** [comment]
That works for me

**Comment by josmithua** [comment]
Actually I lied, it is being used.

Would renaming the Utils extension be enough to fix this?

```diff
-@interface UIViewController (Utils)
+@interface UIViewController (RNMSALUtils)
```

**Comment by ajzozakiewicz** [comment]
Yep, that is exactly what we need. We have tested this in a fork of the repo (internal gitlab) and seems to solve the problem.

**Comment by ajzozakiewicz** [comment]
Just wanted to close the loop on this. Tested and working perfectly. Thanks for the fast update!

**Comment by josmithua** [comment]
Sorry I forgot to ask you to verify if it worked. Glad it is!

Thanks for submitting the issue!
