### ISSUE TITLE
iOS MsalAccount with no claims?

### ISSUE THREAD

**Issue by dan-trewin** [stashenergy/react-native-msal#62]
In the auth flow for my app, I need the `accessToken` from a logged in account for given scopes.
This is the rough flow:
```js
...
const accounts = await pca.getAccounts()
const params = {
   scopes,
   account: accounts[0]
}
const result = await pca.acquireTokenSilent(params)
const jwt = result.accessToken
```
It has worked for me on my iOS device. 
However, on my coworker's iOS device, he is getting back an `MSALAccount` with an undefined `claims` property. We are not sure how or why this happened. According to the typescript file: <https://github.com/stashenergy/react-native-msal/blob/master/src/types.ts#L61> this should be allowed. But he got a native crash that looks like this:
```
Exception '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: claims)' was thrown while invoking getAccounts on target RNMSAL with params (
    48,
    49
)
``` 
We did a bit of digging and found out that even though the typescript file suggests `claims` is optional, if it does in fact come back nil (in the native iOS code), the app hard crashes b/c of this line: <https://github.com/stashenergy/react-native-msal/blob/master/ios/RNMSAL.m#L304>

So, I have one question and two possible solutions:
If a `MSALAccount` comes back with an undefined `claims` property is it still usable? Meaning would I still be able to get an `accessToken` from it using the `pca.acquireTokenSilent` method? 
1. If `MSALAccount` is still usable, I think this line of code needs to be changed so that the app doesn't hard crash in the native code: <https://github.com/stashenergy/react-native-msal/blob/master/ios/RNMSAL.m#L304>
2. If `MSALAccount` is unusable, shouldn't the `pca.getAccounts` method check for a nil `claims` property and return a rejected promise saying the account(s) are corrupt rather than crashing in native code? Alternatively, it could instead go an extra step and log out any corrupt accounts and return an empty array of `MSALAccounts` (though this part could be handled by the app rather than this package if the method returned a unique rejected promise).

Without one of these solutions, I fear our users may run into this strange issue where an `MsalAccount` has no `claims` and it would result in a native crash.

Thanks in advance,
Dan

**Comment by josmithua** [comment]
Hi Dan, thanks for raising this issue.

According to the [MSALAccount protocol](https://azuread.github.io/microsoft-authentication-library-for-objc/Protocols/MSALAccount.html#/c:objc(pl)MSALAccount(py)accountClaims), `accountClaims` can be nullable, so it's a bug with this library and I will fix it ASAP to not crash and return null.

Cheers,

**Comment by dan-trewin** [comment]
Thanks for the quick response!

Great, this gives us more flexibility too, if we find out we can't get access tokens with those accounts (the ones without claims), our js code can check if claims is null and if so log out the account (s).

**Comment by josmithua** [comment]
@dan-trewin let me know how v3.0.5 works.

**Comment by dan-trewin** [comment]
This resolved all our issues. 

Also FYI - for anyone on this thread in the future, the `claims` prop on `MSALAccount` isn't required to retrieve accessTokens. I did some testing this morning and I could still retrieve accessTokens/jwts with a null `claims`.

Thanks!
