### ISSUE TITLE
Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=not found

### ISSUE THREAD

**Issue by sultan-arshi** [stashenergy/react-native-msal#63]
i have read all the doc and setup the IOS environment but i am getting error 
i know i could not generate the `authorityBase` and scops `b2cScopes` that you have used in `msalConfig.ts`

**can you please tell me how can i create all these `b2cScopes`, `authorityBase`, and `policies` urls** 

i have followed doc and perfomed every steps in the `API permissions` and `expose an API` etc. but continuesly getting error below 

> [Error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=not found, MSALHTTPResponseCodeKey=404, MSALCorrelationIDKey=DFBC6058-A06D-4D3C-8967-CC40819549A1, MSALInternalErrorCodeKey=-42007, MSALHTTPHeadersKey=<CFBasicHash 0x6000038e0fc0 [0x7fff8002eb50]>{type = immutable dict, count = 9,
entries =>
	0 : X-Content-Type-Options = nosniff
	1 : Content-Type = text/html
	2 : Allow = <CFString 0x600002333ae0 [0x7fff8002eb50]>{contents = "OPTIONS,TRACE,GET,HEAD,POST"}
	3 : Strict-Transport-Security = <CFString 0x6000038ff800 [0x7fff8002eb50]>{contents = "max-age=31536000; includeSubDomains"}
	4 : Public = <CFString 0x6000023305a0 [0x7fff8002eb50]>{contents = "OPTIONS,TRACE,GET,HEAD,POST"}
	6 : Date = <CFString 0x600002333b10 [0x7fff8002eb50]>{contents = "Thu, 11 Feb 2021 09:17:26 GMT"}
	7 : X-Frame-Options = DENY
	8 : X-XSS-Protection = <CFString 0x600002be0400 [0x7fff8002eb50]>{contents = "1; mode=block"}
	10 : Content-Length = 1245
}
}]

**Comment by josmithua** [comment]
404 means a URL is wrong somewhere. Please double check all your URLs in `msal_config.json`, and in your JavaScript source.

`authorityBase` and `policies` are just based off the full policy URLs. Full B2C policy URLs look like this:
`https://stashcafe.b2clogin.com/tfp/stashcafe.onmicrosoft.com/B2C_1_SignInUp`
`authorityBase` is just the first part, without the policy name: 
`https://stashcafe.b2clogin.com/tfp/stashcafe.onmicrosoft.com`
`policies` is an object with the various policies. `signInsignUp` is required, `passwordReset` is optional

**Comment by sultan-arshi** [comment]
thanks for response 
i have resolved the error and you are right this was error in the URL, i added the userFlow with name `B2C_1_SignInUp` at azure portal and it resolved my issue 
i can login and signup now, but i have different sign in page then you 
can you please tell me why your sample application and my one is different ?
are you using `custom policies` and have made some custom view at `azure portal` ?

**Comment by josmithua** [comment]
Glad you got it working!

Yes you are correct, we are using custom CSS for the pages.
