### ISSUE TITLE
Attempt to invoke interface method 'void com.microsoft.identity.client.IMultipleAccountPublicClientApplication.acquireToken(com.microsoft.identity.client.AcquireTokenParameters)' on a null object reference

### ISSUE THREAD

**Issue by sdevansh96** [stashenergy/react-native-msal#64]
hello MSAL is working fine in ios but in android I am getting this error

Attempt to invoke interface method 'void com.microsoft.identity.client.IMultipleAccountPublicClientApplication.acquireToken(com.microsoft.identity.client.AcquireTokenParameters)' on a null object reference

**Comment by josmithua** [comment]
The Android PublicClientApplication is not being created successfully. I think this could happen if there's something wrong in your `msal_config.json` file, so please double check everything in there.

**Comment by shailesh-sakaria** [comment]
facing the same issue... let me know if any workaround found.

**Comment by josmithua** [comment]
@sdevansh96, are you calling `acquireToken` right after creating the PCA? The PCA class constructor calls an asynchronous function `createPublicClientApplication` which may not be completed before calling `acquireToken`. This is just a theory, I will try to do some testing today.

**Comment by sdevansh96** [comment]
There must be something wrong with my msal_config.json.
Will look into this and let you know if the issue persist.

**Comment by josmithua** [comment]
I would also check your scopes (#67 similar issue)

**Comment by sdevansh96** [comment]
Hello @josmithua ,

You can close this issue.

The problem was in msconfig.js, the new documentation was really helpfull.

**Comment by josmithua** [comment]
Fantastic, glad to hear!
