### ISSUE TITLE
could not invoke RNMSAL.createPublicClientApplication 

### ISSUE THREAD

**Issue by Rana-Abuzar** [stashenergy/react-native-msal#66]
when i run application after msal configuration for android in react native, i got this error.
i have double check the package name and signature hash

i have checked my redirect url in the msalConfigurationfile.json is same as on the azure portal and manifest 

![Screenshot 2021-02-18 at 7 45 33 PM](https://user-images.githubusercontent.com/60849525/108376899-490edf80-7225-11eb-9304-78702037f50e.png)

> Is your config file named `msal_config.json`?

**Comment by josmithua** [comment]
Is your config file named `msal_config.json`?

**Comment by Rana-Abuzar** [comment]
> Is your config file named `msal_config.json`?

**Comment by josmithua** [comment]
Usually the error is right, so please double check the redirect URI in your config file, and in the portal, and make sure the package signatures match and is encoded properly

**Comment by Rana-Abuzar** [comment]
Thanks for reply 
well, i have configure the configuration below 


 in android > app > src > main > assets > msal_config.json
```
{
    "client_id": "My_client-id",
    "authorization_user_agent": "DEFAULT",
    "redirect_uri": "msauth://com.instoremobile/M74kWwKnLGHKWweswsUc5csggBRxjM%3D",
    "account_mode": "MULTIPLE",
    "broker_redirect_uri_registered": true,
    "authorities" : [
        {
          "type": "B2C",
          "authority_url": "https://domain.b2clogin.com/tfp/compnay.onmicrosoft.com/",
          "default": true
        }
      ]
   
}
```
the `Redirect URL` that i made from azure portal is `msauth://com.myPackegeName/M74kWwKnLGHKWweswsUc5csggBRxjM%3D`

in both `manifest` (debug and release) i have activity below 

```
<activity
            android:name="com.microsoft.identity.client.BrowserTabActivity" >
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                    android:scheme="msauth"
                    android:host="com.myPackegeName"
                    android:path="/M74kWwKnLGHKWweswsUc5csggBRxjM=" />
            </intent-filter>
        </activity>
```
the most **important thing** that i would mention here is the `build.gradle` 
i was facing failed build for android and i add one line below in the `defaultConfig`
`manifestPlaceholders = [appAuthRedirectScheme: '/M74kWwKnLGHKWweswsUc5csggBRxjM=']`

i noticed that we are not providing any `custom policies` at android studio side (as i am using custom policies) which are written in the `msalConfig.ts` file as in you sample project, are `custom policies` being used from `msalConfig.ts` file ?

**Comment by josmithua** [comment]
In msal_config.json, please try setting broker_redirect_uri_registered to false, and adding your custom policies. See the msal_config.json file in the example app

**Comment by Rana-Abuzar** [comment]
thanks
the error gone but when i call this `await b2cClient.signIn({scopes, webviewParameters})` function to login,  then  noting happens, no response or catch error. And the same thing is running on iOS.

**Comment by Rana-Abuzar** [comment]
i think, the problem is here in **android > app > build.gradle** 
```
defaultConfig {
        applicationId "com.appname"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        manifestPlaceholders = [appAuthRedirectScheme: 'com.appname']
    }
```
i don't know exactly what to write in **appAuthRedirectScheme**?

**Comment by josmithua** [comment]
You do not need anything related to msal in your build.gradle

**Comment by Rana-Abuzar** [comment]
by this code browser is not opening 
`return await this.pca.acquireToken(params);`

**Comment by Rana-Abuzar** [comment]
then why browser is not opening for android and working perfectly in iOS
`return await this.pca.acquireToken(params);`

**Comment by josmithua** [comment]
There must be something wrong in your Android configuration. It can be tricky as you have experienced, but please go carefully through the setup steps for Android in the README. Also you don’t need to copy the BrowserTabActivity in your debug manifest. 

I’m sorry I can’t help you very much without having more information or access to your project. 

A helpful thing to do is debug your app in Android studio and put breakpoints in the RNMSAL code to see what is being called with what.

**Comment by Rana-Abuzar** [comment]
i just checked it according to your instructions
and found the below promise is not invoked 
you can see in the screen shot blow that not even any break point of `onCancel`, `onSuccess` and `onError` worked


![Screenshot 2021-02-23 at 7 24 39 PM](https://user-images.githubusercontent.com/60849525/108857615-168e2980-760d-11eb-8614-b2e758fe564d.png)

**Comment by josmithua** [comment]
Please see if a breakpoint on line 100 is hit

**Comment by Rana-Abuzar** [comment]
![Screenshot 2021-02-24 at 11 57 55 AM](https://user-images.githubusercontent.com/60849525/108960352-9660d600-7697-11eb-83eb-0879a85737b4.png)


if we see this screen shot line 100 is in `acquireTokenSilent` method which we are not using i think 
so,  break point at line 100 is not working

**Comment by josmithua** [comment]
?? That code is not part of this library, **react-native-msal**. I meant put a breakpoint on [line 100 of RNMSALModule.java](https://github.com/stashenergy/react-native-msal/blob/master/android/src/main/java/com/reactnativemsal/RNMSALModule.java#L100).

Is that your code?

**Comment by josmithua** [comment]
Can I ask why you closed this? Did you find the issue? If so, can you share your solution? Thanks

**Comment by JamieKidman** [comment]
> appAuthRedirectScheme

I cannot see this file in the example app

**Comment by josmithua** [comment]
@JamieKidman you don't need to add `appAuthRedirectScheme` anywhere, Rana was mistaken.
