### ISSUE TITLE
Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by ksingh31** [stashenergy/react-native-msal#67]
Attempt to invoke interface method 'java.util.List com.microsoft.identity.client.IMultipleAccountPublicClientApplication.getAccounts()' on a null object reference.

**Comment by josmithua** [comment]
Please provide more info. Are you using this module for the first time? What version are you using? Have you tried breakpoint debugging in Android Studio?

This might be a bug, as multiple people are reporting the same issue. Are you calling get accounts right after creating the PCA? The PCA class constructor calls an asynchronous function `createPublicClientApplication` which may not be completed before calling `getAccounts`.

**Comment by ksingh31** [comment]
I am using it for the first time and i followed your example here and made required chnages "https://github.com/stashenergy/react-native-msal/tree/master/example/src"

I also updated msal_config.json and AndroidManifest.xml based on my Azure portal.
![image](https://user-images.githubusercontent.com/10522027/109227401-828f9f80-777d-11eb-8a26-9c4dd3c94ff6.png)

**Comment by ksingh31** [comment]
@josmithua I was able to get that working (not sure what went wrong but i created a new project and moved my changes there and it worked). Now the issue I am having is:
**"Error: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference"**

Everything works great, I can see the login dialog, i can input my credentials and log in. But when the browser window closes, I get this error, no token.

AndroidManifest.xml
![image](https://user-images.githubusercontent.com/10522027/109238638-20409a00-7791-11eb-8c00-0837e83a09c7.png)

msal_config.json
![image](https://user-images.githubusercontent.com/10522027/109238671-32223d00-7791-11eb-9818-b4e05f03701e.png)

msalConfig.ts
![image](https://user-images.githubusercontent.com/10522027/109238767-60a01800-7791-11eb-9956-859443ec94a7.png)

Rest of the things are same as the example you provided in that repo

**Comment by josmithua** [comment]
Your `redirect_uri` in `msal_config.json` should be `msauth://<your package name>/<signature hash>`. So in your case, `msauth://com.biostreamreact/ga0R...`.

Also in your AndroidManifest, the host should be `com.biostreamreact`

**Comment by ksingh31** [comment]
I updated those fields but still the same issue

msal_config.json
![image](https://user-images.githubusercontent.com/10522027/109248536-38211980-77a3-11eb-9b3a-3c113a2967d2.png)

AndroidManifest.xml
![image](https://user-images.githubusercontent.com/10522027/109248571-45d69f00-77a3-11eb-86cc-fe14d7cb6f1f.png)

**Comment by ksingh31** [comment]
Thanks for you help, but i was able to resolve the issue. My issue was related to Azure portal Scope related.

**Comment by josmithua** [comment]
Glad you got it working!
