### ISSUE TITLE
Check if user logged in

### ISSUE THREAD

**Issue by dusanjovanov** [stashenergy/react-native-msal#7]
Hi , thank you for this library you saved my life :)

Every time I open the app it opens the login page in browser. Is there a way to first check if the user is already logged in ? Am I missing some config ?

This is my msal_config.json: (some values are omitted)
```
{
  "client_id": "xxxxx",
  "redirect_uri": "msauth://xxxx",
  "authorization_user_agent": "DEFAULT",
  "account_mode": "MULTIPLE",
  "authorities": [
    {
      "type": "B2C",
      "authority_url": "authority/signinsignuppolicy",
      "default": true
    }
...
  ]
}

```

**Comment by josmithua** [comment]
Hi there! I'm glad it's useful to you :).

The library does not handle the logic of checking whether a user is already logged in, you will have to do this yourself in your app. 

Basically, you should check to see if you already have an account identifier stored somewhere in persistent storage (AsyncStorage). If you do, just do a silent login with `acquireTokenSilent` with the identifier. If you don't, do an interactive login with `acquireToken` and make sure to store the account identifier from the result in persistent storage.

**Comment by dusanjovanov** [comment]
Understood, thanks :)
