### ISSUE TITLE
[config] 

### ISSUE THREAD

**Issue by sbatikeri** [stashenergy/react-native-msal#70]
**Before you create an issue:**

Have you:
- [ Yes] Upgraded to the latest version of `react-native-msal`
- [Yes ] Read the README thoroughly
- [ Yes] Searched for other similar issues
- [ ] Used breakpoint debugging in the Swift/Java module code?
- [ ] Tried to reproduce the problem in the example app in this repository?

**Problem description:**
I have multiple environments and I cam creating a unique application id for each build by appending env. I have 2 keystores PROD and NONPROD. Can some one help me how to config multiple redirect urls in msal_config.json.
ex: com.myapp.dev
      com.myapp.qa

 flavorDimensions "default"
    productFlavors {
        dev { 
            dimension "default"
            applicationIdSuffix ".dev"
            versionNameSuffix "-dev"
            resValue "string", "app_name", "MyApp-Dev" 
        }
        qa { 
            dimension "default"
            applicationIdSuffix ".qa"
            versionNameSuffix "-qa"
            resValue "string", "app_name", "MyApp-Alpha"
        }
        uat { 
            dimension "default" 
            applicationIdSuffix ".uat"
            versionNameSuffix "-uat"
            resValue "string", "app_name", "MyApp-Beta"
        }
        prod { 
            dimension "default"
            versionNameSuffix ""
            resValue "string", "app_name", "MyApp"
        }

**Contents of `msal_config.json`:**
```json
{}
```

**Relevant contents of `AndroidManifest.xml`:**
```xml
<activity android:name="com.microsoft.identity.client.BrowserTabActivity">
  ...
</activity
```
**Usage JavaScript/TypeScript code:**
```tsx
const res = await pca.acquireToken(...)
```

**Relevant error messages and screenshots:**
Please provide error messages and screenshots here

**Comment by josmithua** [comment]
I think you need separate AndroidManifest.xml and msal_config.json files for your different environments. It's been a while since I did any Android development, so I'm not sure if I can help you a whole lot

**Comment by sbatikeri** [comment]
I tried adding multiple AndroidManifest.xm inside each environment but not sure where to put mssal_config.json. As per document they mentioned to put inside the assets. 
![image](https://user-images.githubusercontent.com/62160090/111846086-19123500-88d4-11eb-87e3-9d950a7d354b.png)

**Comment by sbatikeri** [comment]
Can some one help me with android set up

**Comment by sbatikeri** [comment]
I am able to fix this. Added build.gradle script to copy msal_config from flavors folders to asset.

**Comment by josmithua** [comment]
You might be able to have flavor-specific  assets without using a script. See https://stackoverflow.com/a/50390875
