### ISSUE TITLE
MSALConfiguration ignored by RNMSALModule.java createPublicClientApplication(ReadableMap params)

### ISSUE THREAD

**Issue by davidkdev** [stashenergy/react-native-msal#72]
Hello,

I found this bug when trying to use different clientIds and changing the clientId during runtime. The config I pass to PublicClientApplication gets passed down to the RNMSALModule.java.

`@ReactMethod`
`    public void createPublicClientApplication(ReadableMap params) {`
`        ReactApplicationContext context = getReactApplicationContext();`
`        try {`
`            InputStream inputStream = context.getAssets().open("msal_config.json");`
     `       System.err.println("-------------------------------PARAMS---------------------------------------------------------``-");`
           ` System.err.println(params);`
          `  System.err.println("-----------------------------------------------------------------------------------------------``");`
         `   File file = File.createTempFile("RNMSAL_msal_config", ".tmp");`
            `file.deleteOnExit();`
      `      FileUtils.copyInputStreamToFile(inputStream, file);`
`            System.err.println("-------------------------------FILE----------------------------------------------------------");`
           ` System.err.println(file);`
`            System.err.println("-----------------------------------------------------------------------------------------------");`
            `publicClientApplication =`
                   ` PublicClientApplication.createMultipleAccountPublicClientApplication(`
                  `          context, file);`
      `  } catch (Exception ignored) {`
 `       }`
`    }`

And I can see the params in the console, when I log them. The next part of the code however ignores the config and just reads the "msal_config.json". I think the behavior should be, that if it gets passed a config it shouldn't read the file and instead use the params.

Are there any plans to fix this?

Thanks!

**Comment by josmithua** [comment]
There are no plans to support changing the clientId at runtime. The underlying MSAL library for Android only supports reading from the file.

**Comment by davidkdev** [comment]
So why don't we parse the params, build a temp file with the params and then pass the temp file to the underlying MSAL library? Should not be a lot of work to get that working or am I wrong? 

I saw the iOS implementation and it works fine, but I develop for both and expected it to work the same way.

**Comment by josmithua** [comment]
Yes I suppose it could be done, and it would make android setup easier (not having to have the `msal_config.json`) and keep the functionality similar between Android and iOS. 

Would you be willing to submit a PR?

**Comment by davidkdev** [comment]
I am willing to so. Will work on it the following days.

**Comment by josmithua** [comment]
@davidkdev Just wondering if you are still planning to work on this or if I should dig in. No pressure, I can find some time to work on it if you aren't available. Cheers!

**Comment by davidkdev** [comment]
@josmithua Hi, we decided to fork it and put in the time to make it work for our use case. We can't afford the time to make it clean, change the params on the react level etc. But we'd love to use your implementation once you are done. Thank you!

**Comment by josmithua** [comment]
No problem, I will try to work on this in the near future.
