### ISSUE TITLE
SignInSign Up and PasswordReset Policy - when opening sign in dialog sometimes it just shows Password Reset userflow instead of Sign In/Up Flow

### ISSUE THREAD

**Issue by ksingh31** [stashenergy/react-native-msal#73]
**Describe the bug**
when opening sign-in dialog sometimes it just shows Password Reset user flow instead of Sign In/Up Flow

**Expected behavior**
Sign In/Up Page should show up all the time

**Screenshots**
![image](https://user-images.githubusercontent.com/10522027/113041053-bbdd7580-9156-11eb-8429-7ab9a94f8343.png)

** Please complete the following information:**
 - `react-native-msal` version: 3.1.0
 - `react-native` version: 0.63.4
 - Platform: Android

**Comment by josmithua** [comment]
Do you have an authority marked as default in your msal_config.json?

See [msal_config.json in the example app](https://github.com/stashenergy/react-native-msal/blob/master/example/android/app/src/main/assets/msal_config.json#L7-L17)

**Comment by ksingh31** [comment]
@josmithua Thanks, that is what was causing the issue for me.
