### ISSUE TITLE
[Android] Need help to configure multiple client id in single msal_config.json

### ISSUE THREAD

**Issue by nabamita-debnath** [stashenergy/react-native-msal#74]
**Problem description:**
We need both AAD and B2C config in single application having different client IDs and different scopes for AAD and B2C. **How can we combine msal config for two different client IDs in a single msal_config.json.** 

Note: We have Separate buttons for AAD and B2C login.

**Contents of `msal_config.json`:**
For AAD the format we are using is below:

{
"client_id": <CLIENT_ID>
"scopes": [<SCOPE>],
"authorization_user_agent": "DEFAULT",
"redirect_uri": <REDIRECT_URL>,
"account_mode": "MULTIPLE",
"broker_redirect_uri_registered": false,
"authorities": [
{
"type": "AAD",
"audience": {
"type": "AzureADMyOrg",
"tenantId": <TENANT_ID>
},
"default": true
}
]
}

for B2C the format used is below:

{
  "client_id": "<CLIENT_ID>",
  "scopes": [<SCOPE>],
  "redirect_uri": <REDIRECT_URI>,
  "account_mode": "MULTIPLE",
  "authorization_user_agent": "DEFAULT",
  "broker_redirect_uri_registered": false,
  "authorities": [
    {
      "type": "B2C",
      "authority_url": <AUTHORITY_URL>,
      "default": true
    }
  ]
}

**Relevant 
screenshots:**
<img width="318" alt="Screenshot 2021-03-31 at 6 55 14 PM" src="https://user-images.githubusercontent.com/44174513/113152540-dba69380-9253-11eb-9580-7fbb37e12039.png">

**Comment by josmithua** [comment]
This is currently not possible. There are changes forthcoming that might help with this, but for now unfortunately it can’t be done
