### ISSUE TITLE
acquireTokenSilent failing sometimes on ios devices. 

### ISSUE THREAD

**Issue by sbatikeri** [stashenergy/react-native-msal#76]
**Describe the bug**
Refresh token scenario failing some times on ios devices. Most of the times we get no account provided error even though we have fallback to read the account information and send it to acquireTokenSilent. I am storing account information on successfully sign in and using that account while refresh token. If userAccount not found from redux I am reading the accounts using pc.getAccounts() and passing it. This whole process works fine in android but sometimes it failing on ios devices. Can some one suggest what is the best way to avoid this issue. 

**To Reproduce**
Pseudocode:
if(tokenExpired){
                If(storedUser == null){
                    Get accounts: MSALAccount[] = await pca.getAccounts()
let msalParams = { scopes: ["User.Read"], account: accounts[0], forceRefresh: true, };
 
      pca.acquireTokenSilent(msalParams)
}else {
read the user account information from redux store and get refresh token 
let msalParams = { scopes: ["User.Read"], account: storedUser, forceRefresh: true, };
 
     pca.acquireTokenSilent(msalParams) 
}}

errors: 
Error Domain=MSALErrorDomain Code=-50002 "(null)" UserInfo={MSALErrorDescriptionKey=No account provided for the silent request. Please call interactive acquireToken request to get an account identifier before calling acquireTokenSilent.}
 
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/62160090/113597602-9098d180-9601-11eb-8cd9-ffcf9d6d8f93.png)

** Please complete the following information:**
 "react-native-msal": "^3.1.0",
  "react-native": "^0.61.5",
 - Platform: IOS
 - Browser (if applicable) All

**Additional context**
I am passing scopes: ["User.Read"]. Is there any other scope like 'offline_access' we need to get this fixed.

if (!isRefreshRequired) {
      Logger.verboseLog("Jwt token is valid.");
      return _api(url, method, request, headers, retryCount, timeOut, jwt);
    } else {
      Logger.verboseLog("Jwt token is expired.");
      console.log("----TOKEN EXPIRED------");
      Logger.logError(new Error("----TOKEN EXPIRED------"));
      Logger.verboseLog("Reading refresh token from secret store.");
      Logger.verboseLog("userAccount: " + JSON.stringify(userAccount))
      
      if(userAccount !== undefined){ 
        return refreshTokenSilent(userAccount,  url,
          method,
          request,
          headers,
          retryCount,
          timeOut
          )
      }else{
        return pca
        .getAccounts()
        .then((accounts: any) => {
          Logger.verboseLog("getAccounts: " + JSON.stringify(accounts))
          return refreshTokenSilent(accounts[0],url,
          method,
          request,
          headers,
          retryCount,
          timeOut)
         });
      }
    }
function refreshTokenSilent(userAccount,  url,
  method,
  request,
  headers,
  retryCount = 2,
  timeOut = null){
    
        const { authentication } = store.getState();
          let msalParams = { scopes: ["User.Read"], account:userAccount, forceRefresh: true, };
              
          Logger.logError(new Error("msalParams:" + JSON.stringify(msalParams)));
          return pca
            .acquireTokenSilent(msalParams)
            .then((response: any) => { 
              Logger.log("Refresh token renewed successfully.");
              console.log(new Date().toISOString());
              const { accessToken, refreshToken, idToken, account } = response;
              saveTokens(accessToken, idToken, idToken, account); // TODO: clean this react-native-msal don't have refresh token
              Logger.logError(new Error("----TOKEN REFRESHED------"));
              return _api(
                url,
                method,
                request,
                headers,
                retryCount,
                timeOut,
                idToken
              );
            })
            .catch(error => {
                  Logger.logError(error);
                  const userName = authentication.get("userName");
                  const userType = authentication.get("userType");
                  console.log("FAILED TO REFRESH TOKEN: ", error);
                  Logger.logError(new Error("----FAILED TO REFRESH TOKEN------"));
                  Logger.logError(new Error("userName:"+ userName + " userType:" + userType));
                  Logger.verboseLog("Refresh token expired.");
                  Logger.verboseLog("Force signout.");
                  Logger.logError(error);
                  signOut();
            });
}

**Comment by sbatikeri** [comment]
I found that lib is not able to find the accounts when I am trying for refresh token. getAccounts() gives [] array.  I guess even thought we pass the account information lib is not able to pull information from cache/keychain and failing.

**Comment by sbatikeri** [comment]
@josmithua can you take a look this issue and let me know if its know issue or not

**Comment by josmithua** [comment]
Sorry @sbatikeri, we use this library in two iOS apps and have not reproduced this issue, although we use B2C.

Btw you said you pass "User.Read" as a scope but in the screenshot it says "email"?

**Comment by sbatikeri** [comment]
> Sorry @sbatikeri, we use this library in two iOS apps and have not reproduced this issue, although we use B2C.
> 
> Btw you said you pass "User.Read" as a scope but in the screenshot it says "email"?

Screenshot was old, Initially I used email. I am seeing same issue even after changing it to "user.read"

**Comment by josmithua** [comment]
> getAccounts() returns empty on first acquireTokenSilent when user installs the app for the first time. It works after user sign in back.

Yes that is how it works. You need to login interactively first, then you can use acquireTokenSilent after that.

**Comment by sbatikeri** [comment]
> > getAccounts() returns empty on first acquireTokenSilent when user installs the app for the first time. It works after user sign in back.
> 
> Yes that is how it works. You need to login interactively first using acquireToken, then you can use acquireTokenSilent after that.

Issue not fixed. 
I am calling interactive sign in and storing the account information for acquireTokenSilent(). When I try for the first time token renewal it failing with No account not found for silent request. On error I am signing out once your sign in back subsequent acquireTokenSilent() calls working fine. It is only problem with first install and first acquireTokenSilent() call. May be on first sign in MSAL not able to store account.
