### ISSUE TITLE
Possible Unhandled Promise Rejection in release app and working fine in debug app

### ISSUE THREAD

**Issue by aditya38112** [stashenergy/react-native-msal#81]
Getting Possible Unhandled Promise Rejection (id: 0):
Error: Attempt to invoke interface method 'void com.microsoft.identity.client.IMultipleAccountPublicClientApplication.acquireToken(com.microsoft.identity.client.AcquireTokenParameters)' on a null object reference

In release app, only this issue is coming and not in debug the app, in debug app it used to come but now it is working fine, and if I use the 2nd method of initializing publicClientapplication and even with timeout of one minute, I get this Possible Unhandled Promise Rejection (id: 0):
Error: PublicClientApplication instance not initialized.

**Comment by josmithua** [comment]
Please see [this comment](https://github.com/stashenergy/react-native-msal/issues/79#issuecomment-824896433)

**Comment by josmithua** [comment]
Your signature hash might not match, or make sure to  set `"broker_redirect_uri_registered": false,` in `msal_config.json`. You can catch errors config errors with 
```js
const pca = new PublicClientApplication(config, false); 
try { 
  await pca.init(); 
} catch (error) { 
  ...
}
```

**Comment by aditya38112** [comment]
Thanks, @josmithua, I previously tried with "broker_redirect_uri_registered": false and it worked, and in no other docs or issue I found this solution, hence was stuck, by the way I tried with different "authorization_user_agent" values but only "WEBVIEW" seem to work, so would not it be good to mention in the docs itself.
