### ISSUE TITLE
acquireTokenSilent error

### ISSUE THREAD

**Issue by dusanjovanov** [stashenergy/react-native-msal#9]
I get this error when calling acquireTokenSilent:
```
Error: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
    at Object.fn [as acquireTokenSilent] (NativeModules.js:99)
    at MSALClient.acquireTokenSilent (index.tsx:89)
    at getTokenSilently$ (auth.ts:27)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:170
    at tryCallTwo (core.js:45)
```

This is how I call it: 
```
await msalClient.acquireTokenSilent({
      authority,
      scopes,
      accountIdentifier: identifier,
    });
```

The params are good, I checked them. But when I force him to login again, it works. Is it maybe that the token has expired and I have to refresh it manually somehow ?

**Comment by josmithua** [comment]
Hi there, and sorry for the delayed response.

By the error it looks like you are specifying a string somewhere where it is expecting an object. Please check your `msal_config.json` file and all the parameters you are passing.

**Comment by dusanjovanov** [comment]
This is what my account identifier looks like : 
`c2d63ecc-fad7-4790-928d-9506244b63e0-b2c_1a_gsh_signuporsignin`. 

This is my msal_config.json :
```
{
  "client_id": "38fc8f67....",
  "redirect_uri": "msauth://com.xxx/LSRuI9E...",
  "authorization_user_agent": "DEFAULT",
  "account_mode": "MULTIPLE",
  "authorities": [
    {
      "type": "B2C",
      "authority_url": "https://xxx.b2clogin.com/tfp/xxx.onmicrosoft.com/B2C_1A_GSH_SignUpOrSignIn/",
      "default": true
    },
    {
      "type": "B2C",
      "authority_url": "https://xxx.b2clogin.com/tfp/xxx.onmicrosoft.com/B2C_1A_GSH_ProfileEdit/"
    },
    {
      "type": "B2C",
      "authority_url": "https://xxx.b2clogin.com/tfp/xxx.onmicrosoft.com/B2C_1A_GSH_PasswordReset/"
    }
  ]
}

```

**Comment by dusanjovanov** [comment]
I actually get that error when the token expires and I call acquireTokenSilent. How should I refresh the token ? Thanks in advance :)

**Comment by josmithua** [comment]
Interesting. I thought the token refreshed automatically when needed. I will look into this further. But you can call acquireTokenSilent with the forceRefresh option set to true to get a new token

**Comment by dusanjovanov** [comment]
Sorry, my mistake, the authority argument I was passing to acquireTokenSilent was wrong. Closing the issue now.
