### ISSUE TITLE
[Error: Attempt to invoke interface method 'com.facebook.react.bridge.ReadableArray com.facebook.react.bridge.ReadableMap.getArray(java.lang.String)' on a null object reference]

### ISSUE THREAD

**Issue by paulorod07** [stashenergy/react-native-msal#94]
I am trying to login with microsoft with react-native-msal

this is working good on IOS but on Android I am getting this error:

[Error: Attempt to invoke interface method 'com.facebook.react.bridge.ReadableArray com.facebook.react.bridge.ReadableMap.getArray(java.lang.String)' on a null object reference]

 - `react-native-msal` version: [3.1.1]
 - `react-native` version: [0.63.4]
 - Platform: [Android]

**Comment by tanujchawla** [comment]
@josmithua Could you please help me resolve this?

**Comment by josmithua** [comment]
When does this happen? On init or when calling acquireToken?

**Comment by tanujchawla** [comment]
@josmithua This is happening when calling `acquireToken`.

**Comment by josmithua** [comment]
What does your scopes parameter look like?

**Comment by tanujchawla** [comment]
@josmithua 

Currently we are not sending any scopes parameter as we have not defined it in our app on Azure portal.

I'm calling `acquireToken` without any parameters.

`const result = await pca.acquireToken();`

**Comment by josmithua** [comment]
Ah there's the issue. You need to specify at the bare minimum the `scopes` option. You can set it to an empty array if you wish:

```js
const result = await pca.acquireToken({ scopes: [] });
```

**Comment by tanujchawla** [comment]
@josmithua 
We tried that, but it gave us an error as `Empty scopes list`.

We added a couple of scopes and it is working fine now.

Thank you so much for your help :)

**Comment by josmithua** [comment]
Ok, I will update the docs to make it clear that you need to provide at least one scope. Thanks!
