### ISSUE TITLE
Error: PublicClientApplication instance not initialized. on iOS

### ISSUE THREAD

**Issue by davidkdev** [stashenergy/react-native-msal#95]
Hi developers,

I have a weird problem with this library, it is working fine on android, interactive login is working, acquiring tokens silently, everything works like a charm on android.

On iOS however, with the same codebase, I get the following error:

`Error: PublicClientApplication instance not initialized.`

The following code is the way I acquire a Token interactively:

 ```
export const acquireToken = async (account?: MSALAccount) => {
  const apiEnvironment = store.getState().API.apiEnvironment;


 const scopes = [apiEnvironment.scope];

  const pca = await new PublicClientApplication(getMSALConfiguration());

  interface TokenDto {
    sub: string;
    given_name: string;
    family_name: string;
  }

  let tmpAccount = account;

  try {
    if (!tmpAccount) {
      const result = await pca.acquireToken(getMSALInteractiveParams());
      console.log('resultAquireToken:', result);
      if (result.idToken) {
        let jwtdecoded: TokenDto = jwt_decode<TokenDto>(result.idToken);
        console.log(
          jwtdecoded.sub,
          ' ',
          jwtdecoded.given_name,
          ' ',
          jwtdecoded.family_name,
        );
      }
      tmpAccount = result.account;
    }
    const resultSilent = await pca.acquireTokenSilent({
      account: tmpAccount,
      scopes: scopes,
    });
    return resultSilent;
  } catch (error) {
    console.log(error);
    return error;
  }
}
```
Do you have any idea why this is happening?

Thank you in advance.

David

**Comment by josmithua** [comment]
Please use the init method as described [here](https://github.com/stashenergy/react-native-msal#creating-an-instance). See also #79

**Comment by ksingh31** [comment]
@josmithua I have the same error as well on ios, and tried making changes based on your comment, but wasn't able to get it working. In that demo Github code can you point where exactly do we need to make that fix and exactly what to do. Thanks.

**Comment by josmithua** [comment]
@ksingh31 I've updated the example app code, please see [example/src/App.tsx](https://github.com/stashenergy/react-native-msal/blob/master/example/src/App.tsx#L11-L33) and [example/src/b2cClient.ts](https://github.com/stashenergy/react-native-msal/blob/master/example/src/b2cClient.ts).

**Comment by ksingh31** [comment]
@josmithua Thanks a lot, that helped
