### ISSUE TITLE
Only one interactive session is allowed at a time

### ISSUE THREAD

**Issue by sdevansh96** [stashenergy/react-native-msal#96]
**Describe the bug**
Hello, 

I am getting this error.

Error: Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Only one interactive session is allowed at a time., MSALInternalErrorCodeKey=-42402, MSALCorrelationIDKey=16786E71-3808-4F4D-9064-208C4E676A13}

msal is working fine and I am able to login, but at the start I am always getting this error.

**Expected behavior**
The error should not come

** Please complete the following information:**
 - `react-native-msal` version: [3.1.1]
 - `react-native` version: [0.64.1]
 - Platform: [IOS]

**Comment by josmithua** [comment]
Please make sure you are only calling `acquireToken` once
