### ISSUE TITLE
Extra scopes are not shown for consent on Android

### ISSUE THREAD

**Issue by SirElTomato** [stashenergy/react-native-msal#98]
**Describe the bug**
Extra consent scopes are not shown on the consent screen for Android. They are there on iOS. 

**To Reproduce**
Authenticating using the below code: 
```
private readonly kScopes = [
        'api://[*clientId*]/ScanEmails'
    ];

    private readonly kExtraScopes = [
        "mail.read"
    ];
    private readonly kClientId = '[*clientId*]';

    private _msalClient?: PublicClientApplication;
    private _msalConfig = { auth: { clientId: this.kClientId } };

    constructor() {
        // this._msalClient = new PublicClientApplication({ auth: { clientId: this.kClientId } });
    }

    login() {
        return new Promise<boolean>(async (resolve) => {

            const acquireTokenParams: MSALInteractiveParams = {
                scopes: this.kScopes,
                promptType: MSALPromptType.CONSENT,
                extraScopesToConsent: this.kExtraScopes
            };

            try {
                this._msalClient = new PublicClientApplication(this._msalConfig, false);
                await this._msalClient.init();
                const result: MSALResult = await this._msalClient.acquireToken(acquireTokenParams);
                const resultString = JSON.stringify(result);
                if (result && result.accessToken) {
                    console.log(result.accessToken);
                    const response = await MyApi.GenerateMicrosoftApiTokens({ jwt: result.accessToken, scopes: this.kScopes })
                    resolve(response.success);
                }
                else {
                    resolve(false);
                }
                console.log(resultString);

            } catch (error) {
                const jsonError = JSON.stringify(error);
                console.log(jsonError);
                resolve(false);
            }
        })
    }
```

**Expected behavior**
The mail.read scope should appear in the consent screen. It appears if using iOS.

**Screenshots**
Android, mail.read consent is not shown:
![image](https://user-images.githubusercontent.com/25449039/127460341-4d15455e-1789-4131-ae1f-c9a5b586cbb5.png)

** Please complete the following information:**
 - `react-native-msal` version: 3.1.2
 - `react-native` version: 4.10.1
 - Platform: Android
 - Browser (if applicable) [e.g. chrome, safari]

**Additional context**

**Comment by lukaspechar** [comment]
Here is an iOS screenshot clearly showing the `Read your emails` scope. 
![simulator_screenshot_BD849657-53F6-4011-8487-1B4FF6F5AF54](https://user-images.githubusercontent.com/592348/127472678-7eb6ee5c-59d9-4a4b-8781-b6e6ac21545f.png)

**Comment by lukaspechar** [comment]
This is still an issue. Has anyone from the team looked at this? @josmithua

**Comment by josmithua** [comment]
Not yet, but I’ll put it on my todo list

**Comment by SirElTomato** [comment]
Any update on this? Unfortunately if this isn't fixed very soon we will have to stop using this package.

**Comment by josmithua** [comment]
Are you able to debug in android studio?

**Comment by SirElTomato** [comment]
This is react native, how do you want me to debug in android studio?

**Comment by lukaspechar** [comment]
I'll have a look if I can set the debugger for this.

**Comment by lukaspechar** [comment]
Apologies for the delay, finally had some time to look into this. I've attached a screenshot where it is clear that all the parameters are being passed up until the ```CommandDispatcher``` executes the command. At that point Microsoft has all the required parameters sent and control is handed to the web view. The permissions window is shown after login but no "Read your emails" permission is shown. I'll reiterate that this is not an issue with iOS.


![Screenshot 2021-09-22 at 17 12 53](https://user-images.githubusercontent.com/592348/134378464-edcbeba8-a140-4ab1-b19a-47e96eee1db4.png)

**Comment by josmithua** [comment]
Thank you very much @lukaspechar for doing the investigation.

If everything is being passed to the native Android MSAL library, then the issue is probably with it (or possibly your tenant), and not with `react-native-msal`.
